/**
 * useStripePayments.ts
 * React Query hooks for Stripe payment backend functions.
 * Uses optional chaining (actor.methodName?.()) to gracefully handle
 * cases where bindings are not yet generated by pnpm bindgen.
 */

import { useActor } from "@caffeineai/core-infrastructure";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { createActor } from "../backend";
import { useAuth } from "./useAuth";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type ActorAny = any;

// ─── Types (local mirrors — replaced by bindgen output after next build) ────────

export interface StripeHealthStatus {
  status: string;
  keysConfigured: boolean;
  webhookConfigured: boolean;
  lastWebhookReceived: bigint | null;
}

export interface WebhookLogEntry {
  eventId: string;
  eventType: string;
  userId?: string;
  amountCents?: number;
  status: "processed" | "failed" | "skipped";
  processedAt: bigint;
}

export interface FailedWebhookEvent {
  id: string;
  stripeEventId: string;
  eventType: string;
  errorMessage: string;
  retryCount: number;
  createdAt: bigint;
}

export interface RevenueStats {
  today: number;
  week: number;
  month: number;
  activeSubscribers: number;
}

export interface PaymentBannerState {
  bannerType: "success" | "failure";
  message: string;
  daysAdded?: number;
}

// ─── Checkout Session ─────────────────────────────────────────────────────────

/**
 * Creates a Stripe Checkout Session and redirects to the returned URL.
 * On success: window.location.href = url
 */
export function useCreateStripeCheckoutSession() {
  const { actor, isFetching } = useActor(createActor);
  const { isAuthenticated } = useAuth();

  return useMutation<string, Error, { priceId: string; userId?: string }>({
    mutationFn: async ({ priceId, userId = "" }) => {
      if (!actor || isFetching || !isAuthenticated)
        throw new Error("Not ready");
      const result = await (actor as ActorAny).createStripeCheckoutSession?.(
        priceId,
        userId,
      );
      if (!result) throw new Error("Backend method not available");
      if (result.__kind__ === "err") throw new Error(result.err);
      return result.ok as string;
    },
    onSuccess: (url: string) => {
      window.location.href = url;
    },
  });
}

// ─── Customer Portal ─────────────────────────────────────────────────────────

/**
 * Creates a Stripe Customer Portal session and redirects to the returned URL.
 */
export function useCreateStripePortalSession() {
  const { actor, isFetching } = useActor(createActor);
  const { isAuthenticated } = useAuth();

  return useMutation<string, Error, void>({
    mutationFn: async () => {
      if (!actor || isFetching || !isAuthenticated)
        throw new Error("Not ready");
      const result = await (actor as ActorAny).createStripePortalSession?.();
      if (!result) throw new Error("Backend method not available");
      if (result.__kind__ === "err") throw new Error(result.err);
      return result.ok as string;
    },
    onSuccess: (url: string) => {
      window.location.href = url;
    },
  });
}

// ─── Payment Banner ───────────────────────────────────────────────────────────

/** Fetches the current payment banner state (success or failure). */
export function useGetPaymentBanner() {
  const { actor, isFetching } = useActor(createActor);
  const { isAuthenticated } = useAuth();

  return useQuery<PaymentBannerState | null>({
    queryKey: ["paymentBanner"],
    queryFn: async () => {
      if (!actor) return null;
      const result = await (actor as ActorAny).getPaymentBanner?.();
      if (result === undefined || result === null) return null;
      // Unwrap Option<T>: [{__kind__:"Some", value:...}] or []
      if (Array.isArray(result)) {
        if (result.length === 0) return null;
        return result[0] as PaymentBannerState;
      }
      return result as PaymentBannerState;
    },
    enabled: !!actor && !isFetching && isAuthenticated,
    staleTime: 30_000,
    refetchInterval: 60_000,
  });
}

/** Dismisses the current payment banner. */
export function useDismissPaymentBanner() {
  const { actor, isFetching } = useActor(createActor);
  const { isAuthenticated } = useAuth();
  const queryClient = useQueryClient();

  return useMutation<void, Error, void>({
    mutationFn: async () => {
      if (!actor || isFetching || !isAuthenticated) return;
      await (actor as ActorAny).dismissPaymentBanner?.();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["paymentBanner"] });
    },
  });
}

// ─── Stripe Health ────────────────────────────────────────────────────────────

/** Returns Stripe connection status, key configuration, and last webhook time. */
export function useGetStripeHealthStatus() {
  const { actor, isFetching } = useActor(createActor);

  return useQuery<StripeHealthStatus | null>({
    queryKey: ["stripeHealth"],
    queryFn: async () => {
      if (!actor) return null;
      const result = await (actor as ActorAny).getStripeHealthStatus?.();
      if (!result) return null;
      return result as StripeHealthStatus;
    },
    enabled: !!actor && !isFetching,
    staleTime: 30_000,
    refetchInterval: 60_000,
  });
}

// ─── Webhook Log ──────────────────────────────────────────────────────────────

/** Returns the last 50 webhook events (admin only). */
export function useGetWebhookLog() {
  const { actor, isFetching } = useActor(createActor);

  return useQuery<WebhookLogEntry[]>({
    queryKey: ["webhookLog"],
    queryFn: async () => {
      if (!actor) return [];
      const result = await (actor as ActorAny).getWebhookLog?.();
      if (!result) return [];
      return result as WebhookLogEntry[];
    },
    enabled: !!actor && !isFetching,
    staleTime: 30_000,
    refetchInterval: 30_000,
  });
}

// ─── Failed Webhook Events ────────────────────────────────────────────────────

/** Returns failed webhook events that need manual retry (admin only). */
export function useGetFailedWebhookEvents() {
  const { actor, isFetching } = useActor(createActor);

  return useQuery<FailedWebhookEvent[]>({
    queryKey: ["failedWebhookEvents"],
    queryFn: async () => {
      if (!actor) return [];
      const result = await (actor as ActorAny).getFailedWebhookEvents?.();
      if (!result) return [];
      return result as FailedWebhookEvent[];
    },
    enabled: !!actor && !isFetching,
    staleTime: 30_000,
    refetchInterval: 60_000,
  });
}

// ─── Retry Failed Event ───────────────────────────────────────────────────────

/** Manually retries a failed webhook event (admin only). */
export function useRetryFailedWebhookEvent() {
  const { actor, isFetching } = useActor(createActor);
  const queryClient = useQueryClient();

  return useMutation<void, Error, { eventId: string }>({
    mutationFn: async ({ eventId }) => {
      if (!actor || isFetching) throw new Error("Not ready");
      const result = await (actor as ActorAny).adminRetryFailedWebhookEvent?.(
        eventId,
      );
      if (!result) return;
      if (result.__kind__ === "err") throw new Error(result.err);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["failedWebhookEvents"] });
      queryClient.invalidateQueries({ queryKey: ["webhookLog"] });
    },
  });
}

// ─── Revenue Stats ────────────────────────────────────────────────────────────

/** Returns revenue summary stats (admin only). */
export function useGetRevenueStats() {
  const { actor, isFetching } = useActor(createActor);

  return useQuery<RevenueStats | null>({
    queryKey: ["revenueStats"],
    queryFn: async () => {
      if (!actor) return null;
      const result = await (actor as ActorAny).getRevenueStats?.();
      if (!result) return null;
      return result as RevenueStats;
    },
    enabled: !!actor && !isFetching,
    staleTime: 60_000,
    refetchInterval: 120_000,
  });
}
