/**
 * useStripePayments.ts
 * React Query hooks for Stripe payment backend functions.
 * Uses optional chaining (actor.methodName?.()) to gracefully handle
 * cases where bindings are not yet generated by pnpm bindgen.
 *
 * ICP Architecture: No webhooks. Payment flow is:
 *   1. createCheckoutSession(priceId) -> get Stripe URL
 *   2. Redirect user to Stripe URL
 *   3. User returns to /payment-success?session_id=XXX
 *   4. verifyAndGrantPayment(sessionId) -> canister verifies with Stripe API
 */

import { useActor } from "@caffeineai/core-infrastructure";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { createActor } from "../backend";
import { useAuth } from "./useAuth";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type ActorAny = any;

// Types

export interface StripeHealthStatus {
  status: string;
  keysConfigured: boolean;
  // ICP architecture: payment verification is polling-based, no webhooks
}

export interface RevenueStats {
  today: number;
  week: number;
  month: number;
  activeSubscribers: number;
}

export interface PaymentBannerState {
  bannerType: "success" | "failure";
  message: string;
  daysAdded?: number;
}

// Checkout Session

export function useCreateStripeCheckoutSession() {
  const { actor, isFetching } = useActor(createActor);
  const { isAuthenticated } = useAuth();

  return useMutation<string, Error, { priceId: string; userId?: string }>({
    mutationFn: async ({ priceId, userId = "" }) => {
      if (!actor || isFetching || !isAuthenticated)
        throw new Error("Not ready — please try again in a moment.");
      const result = await (actor as ActorAny).createStripeCheckoutSession?.(
        priceId,
        userId,
      );
      if (!result) throw new Error("Backend checkout method not available.");
      if (typeof result === "string") return result;
      if (result.__kind__ === "err")
        throw new Error(
          (result.err as string) || "Payment setup failed. Please try again.",
        );
      if (result.__kind__ === "ok") return result.ok as string;
      throw new Error("Unexpected response from payment backend.");
    },
    onSuccess: (url: string) => {
      if (url) window.location.href = url;
    },
    onError: (err: Error) => {
      console.error("[Stripe Checkout]", err.message);
    },
  });
}

// Verify And Grant Payment

export function useVerifyAndGrantPayment() {
  const { actor, isFetching } = useActor(createActor);
  const { isAuthenticated } = useAuth();
  const queryClient = useQueryClient();

  return useMutation<string, Error, { sessionId: string }>({
    mutationFn: async ({ sessionId }) => {
      if (!actor || isFetching || !isAuthenticated)
        throw new Error("Not ready — please try again in a moment.");
      const result = await (actor as ActorAny).verifyAndGrantPayment?.(
        sessionId,
      );
      if (!result)
        throw new Error("Payment verification method not available.");
      if (result.__kind__ === "err")
        throw new Error(
          (result.err as string) || "Payment verification failed.",
        );
      if (result.__kind__ === "ok") return result.ok as string;
      throw new Error("Unexpected response from payment backend.");
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["subscription"] });
      queryClient.invalidateQueries({ queryKey: ["profile"] });
      queryClient.invalidateQueries({ queryKey: ["gasWallet"] });
      queryClient.invalidateQueries({ queryKey: ["paymentBanner"] });
    },
    onError: (err: Error) => {
      console.error("[Stripe Verify]", err.message);
    },
  });
}

// Customer Portal

export function useCreateStripePortalSession() {
  const { actor, isFetching } = useActor(createActor);
  const { isAuthenticated } = useAuth();

  return useMutation<string, Error, void>({
    mutationFn: async () => {
      if (!actor || isFetching || !isAuthenticated)
        throw new Error("Not ready");
      const result = await (actor as ActorAny).createStripePortalSession?.();
      if (!result) throw new Error("Backend method not available");
      if (result.__kind__ === "err") throw new Error(result.err);
      return result.ok as string;
    },
    onSuccess: (url: string) => {
      window.location.href = url;
    },
  });
}

// Payment Banner

export function useGetPaymentBanner() {
  const { actor, isFetching } = useActor(createActor);
  const { isAuthenticated } = useAuth();

  return useQuery<PaymentBannerState | null>({
    queryKey: ["paymentBanner"],
    queryFn: async () => {
      if (!actor) return null;
      const result = await (actor as ActorAny).getPaymentBanner?.();
      if (result === undefined || result === null) return null;
      if (Array.isArray(result)) {
        if (result.length === 0) return null;
        return result[0] as PaymentBannerState;
      }
      return result as PaymentBannerState;
    },
    enabled: !!actor && !isFetching && isAuthenticated,
    staleTime: 30_000,
    refetchInterval: 60_000,
  });
}

export function useDismissPaymentBanner() {
  const { actor, isFetching } = useActor(createActor);
  const { isAuthenticated } = useAuth();
  const queryClient = useQueryClient();

  return useMutation<void, Error, void>({
    mutationFn: async () => {
      if (!actor || isFetching || !isAuthenticated) return;
      await (actor as ActorAny).dismissPaymentBanner?.();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["paymentBanner"] });
    },
  });
}

// Stripe Health

export function useGetStripeHealthStatus() {
  const { actor, isFetching } = useActor(createActor);

  return useQuery<StripeHealthStatus | null>({
    queryKey: ["stripeHealth"],
    queryFn: async () => {
      if (!actor) return null;
      const result = await (actor as ActorAny).getStripeHealthStatus?.();
      if (!result) return null;
      return result as StripeHealthStatus;
    },
    enabled: !!actor && !isFetching,
    staleTime: 30_000,
    refetchInterval: 60_000,
  });
}

// Revenue Stats

export function useGetRevenueStats() {
  const { actor, isFetching } = useActor(createActor);

  return useQuery<RevenueStats | null>({
    queryKey: ["revenueStats"],
    queryFn: async () => {
      if (!actor) return null;
      const result = await (actor as ActorAny).getRevenueStats?.();
      if (!result) return null;
      return {
        today: Number((result as ActorAny).today ?? 0),
        week: Number((result as ActorAny).week ?? 0),
        month: Number((result as ActorAny).month ?? 0),
        activeSubscribers: Number((result as ActorAny).activeSubscribers ?? 0),
      } as RevenueStats;
    },
    enabled: !!actor && !isFetching,
    staleTime: 60_000,
    refetchInterval: 120_000,
  });
}

// Admin: Set Stripe Keys

export function useAdminSetStripeKeys() {
  const { actor, isFetching } = useActor(createActor);
  const queryClient = useQueryClient();

  return useMutation<
    void,
    Error,
    { publishableKey: string; secretKey: string; mode: string }
  >({
    mutationFn: async ({ publishableKey, secretKey, mode }) => {
      if (!actor || isFetching) throw new Error("Not ready");
      const result = await (actor as ActorAny).adminSetStripeKeys?.(
        publishableKey,
        secretKey,
        mode,
      );
      if (!result) return;
      if (result.__kind__ === "err") throw new Error(result.err as string);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["stripeHealth"] });
    },
  });
}

// Admin: Set Stripe Prices

export function useAdminSetStripePrices() {
  const { actor, isFetching } = useActor(createActor);
  const queryClient = useQueryClient();

  return useMutation<
    void,
    Error,
    {
      priceWalker: string;
      priceTraveler: string;
      priceLord: string;
      priceBackup: string;
    }
  >({
    mutationFn: async ({
      priceWalker,
      priceTraveler,
      priceLord,
      priceBackup,
    }) => {
      if (!actor || isFetching) throw new Error("Not ready");
      const result = await (actor as ActorAny).adminSetStripePrices?.(
        priceWalker,
        priceTraveler,
        priceLord,
        priceBackup,
      );
      if (!result) return;
      if (result.__kind__ === "err") throw new Error(result.err as string);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["stripeHealth"] });
    },
  });
}

// Admin: Test Stripe Connection

export function useTestStripeConnection() {
  const { actor, isFetching } = useActor(createActor);

  return useMutation<
    { chargesEnabled: boolean; accountId: string },
    Error,
    { secretKey: string }
  >({
    mutationFn: async ({ secretKey }) => {
      if (!actor || isFetching) throw new Error("Not ready");
      const result = await (actor as ActorAny).adminTestStripeConnection?.(
        secretKey,
      );
      if (!result)
        throw new Error("Test connection method not available in backend.");
      if (result.__kind__ === "err") throw new Error(result.err as string);
      if (result.__kind__ === "ok") {
        const raw = result.ok as string;
        const chargesEnabled =
          raw.includes("charges_enabled:true") ||
          raw.includes('"charges_enabled":true');
        const idMatch = raw.match(/id[":]+([^",}]+)/);
        return {
          chargesEnabled,
          accountId: idMatch?.[1] ?? "—",
        };
      }
      throw new Error("Unexpected response.");
    },
  });
}

// Canister Cycles Balance

export function useGetCanisterCyclesBalance() {
  const { actor, isFetching } = useActor(createActor);

  return useQuery<bigint | null>({
    queryKey: ["canisterCyclesBalance"],
    queryFn: async () => {
      if (!actor) return null;
      const result = await (actor as ActorAny).getCanisterCyclesBalance?.();
      if (result === undefined || result === null) return null;
      return BigInt(result as bigint);
    },
    enabled: !!actor && !isFetching,
    staleTime: 60_000,
    refetchInterval: 120_000,
  });
}
