import { Layout } from "@/components/Layout";
import { useNavigate } from "@tanstack/react-router";
import { ArrowLeft } from "lucide-react";

function Section({
  id,
  title,
  children,
}: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="mb-10">
      <h2 className="legal-section-title">{title}</h2>
      <div className="legal-body">{children}</div>
    </section>
  );
}

export function PrivacyPolicyPage() {
  const navigate = useNavigate();
  const lastUpdated = "April 26, 2026";

  return (
    <Layout>
      <div
        className="max-w-3xl mx-auto px-4 sm:px-6 py-10"
        data-ocid="privacy-policy.page"
      >
        {/* Back navigation */}
        <button
          type="button"
          onClick={() => navigate({ to: "/dashboard" })}
          className="flex items-center gap-2 font-mono text-xs text-muted-foreground hover:text-foreground transition-smooth mb-8 group"
          data-ocid="privacy.back-button"
        >
          <ArrowLeft className="w-3.5 h-3.5 group-hover:-translate-x-0.5 transition-transform" />
          BACK TO DASHBOARD
        </button>

        {/* Header */}
        <div className="mb-8 pb-8 border-b border-border/40">
          <div className="font-mono text-[10px] text-muted-foreground uppercase tracking-widest mb-2">
            LEGAL DOCUMENT — PRIVACY POLICY
          </div>
          <h1 className="legal-title">Privacy Policy</h1>
          <p className="font-mono text-xs text-muted-foreground">
            Last updated: {lastUpdated} &nbsp;·&nbsp; Effective immediately
          </p>
        </div>

        {/* Introduction */}
        <p className="legal-body mb-8">
          At <strong className="text-foreground">Copie Past-e</strong>, we are
          committed to protecting your privacy. This Privacy Policy explains how
          we collect, use, disclose, and safeguard your information when you use
          our platform. Please read this policy carefully. If you disagree with
          its terms, please discontinue use of the service.
        </p>

        <Section id="collection" title="1. Information We Collect">
          <p>
            We collect information you provide directly and information
            generated by your use of our service:
          </p>
          <ul className="legal-list mt-4">
            <li>
              <strong className="text-foreground">Account Data:</strong> Your
              Internet Identity principal (a pseudonymous cryptographic
              identifier), username, and optional profile information.
            </li>
            <li>
              <strong className="text-foreground">Listing Data:</strong> Titles,
              descriptions, prices, categories, tags, and images you upload for
              your product listings.
            </li>
            <li>
              <strong className="text-foreground">Usage Data:</strong> Pages
              visited, features used, timestamps of actions, and error logs
              generated by your interactions with the platform.
            </li>
            <li>
              <strong className="text-foreground">Payment Data:</strong>{" "}
              Subscription status and billing history. Full payment card details
              are processed by Stripe and never stored on our servers.
            </li>
            <li>
              <strong className="text-foreground">Support Data:</strong>{" "}
              Messages and attachments you submit via our support system.
            </li>
            <li>
              <strong className="text-foreground">Extension Data:</strong>{" "}
              Platform detection signals and autofill interaction events
              generated by the Chrome extension.
            </li>
          </ul>
        </Section>

        <Section id="use" title="2. How We Use Your Information">
          <p>We use the information we collect to:</p>
          <ul className="legal-list mt-4">
            <li>Provide, maintain, and improve the Copie Past-e service.</li>
            <li>Process payments and manage your subscription.</li>
            <li>Respond to your support requests and inquiries.</li>
            <li>
              Send important service notifications (account changes, billing
              alerts, security notices).
            </li>
            <li>Monitor system health, detect fraud, and prevent abuse.</li>
            <li>
              Analyze usage patterns to improve features and user experience.
            </li>
            <li>Comply with legal obligations.</li>
          </ul>
          <p className="mt-4">
            We do <strong className="text-foreground">not</strong> sell your
            personal data to third parties. We do not use your listing content
            for advertising or train AI models on your proprietary data.
          </p>
        </Section>

        <Section id="storage" title="3. Data Storage and Retention">
          <p>
            All user data is stored on the{" "}
            <strong className="text-foreground">
              Internet Computer Protocol (ICP)
            </strong>{" "}
            blockchain infrastructure via Motoko canisters. Data is distributed
            and replicated across the ICP network.
          </p>
          <div className="border border-accent/30 bg-accent/5 rounded p-4 font-mono text-xs text-accent mt-4">
            ⚠ PLACEHOLDER — Specify precise data retention periods for each data
            category: (a) Active listings, (b) Archived listings after account
            cancellation, (c) Support tickets, (d) Payment history, (e) Activity
            logs. Also specify the process for requesting data deletion.
          </div>
          <ul className="legal-list mt-4">
            <li>
              Archived listings from expired subscriptions are retained for 30
              days before permanent deletion.
            </li>
            <li>
              Backup snapshots are retained for a limited period for disaster
              recovery purposes.
            </li>
            <li>
              You may request deletion of your data by contacting support.
            </li>
          </ul>
        </Section>

        <Section id="sharing" title="4. Sharing Your Information">
          <p>We may share your information with:</p>
          <ul className="legal-list mt-4">
            <li>
              <strong className="text-foreground">Stripe:</strong> Payment
              processing. Stripe's privacy policy applies to payment card data.
              We share only what Stripe needs to process your subscription.
            </li>
            <li>
              <strong className="text-foreground">Google (Gemini):</strong> When
              you use the Smart OCR feature, images are sent to the Google
              Gemini API for analysis. Images are not stored by Google beyond
              the processing window.
            </li>
            <li>
              <strong className="text-foreground">Law enforcement:</strong> We
              may disclose information when required by law or in response to
              valid legal processes.
            </li>
          </ul>
          <p className="mt-4">
            We do not share your data with marketplace platforms (Facebook,
            eBay, etc.) — your listing content stays on Copie Past-e until you
            choose to post it manually.
          </p>
        </Section>

        <Section id="security" title="5. Security">
          <p>
            We implement industry-standard security measures to protect your
            data, including:
          </p>
          <ul className="legal-list mt-4">
            <li>All data is encrypted in transit via HTTPS/TLS.</li>
            <li>
              Authentication is handled via Internet Identity — no passwords are
              stored.
            </li>
            <li>
              Access to production systems is restricted to authorized
              personnel.
            </li>
            <li>Regular security audits and code reviews are performed.</li>
            <li>
              Canister upgrade safety protocols prevent accidental data loss.
            </li>
          </ul>
          <p className="mt-4">
            No method of transmission over the internet or electronic storage is
            100% secure. We cannot guarantee absolute security, but we are
            committed to using commercially reasonable measures.
          </p>
        </Section>

        <Section id="rights" title="6. Your Rights">
          <div className="border border-accent/30 bg-accent/5 rounded p-4 font-mono text-xs text-accent">
            ⚠ PLACEHOLDER — Enumerate applicable user rights based on
            jurisdiction: GDPR (EU/EEA): right to access, rectification,
            erasure, portability, restriction, objection. CCPA (California):
            right to know, delete, opt-out of sale, non-discrimination. Specify
            how users can exercise these rights and the response timeline (e.g.,
            30 days).
          </div>
          <p className="mt-4">Regardless of jurisdiction, you may:</p>
          <ul className="legal-list mt-4">
            <li>
              Access and export your listing data via the Admin &gt; Data
              Snapshots feature.
            </li>
            <li>
              Delete your account and request data removal by contacting
              support.
            </li>
            <li>Update your profile information at any time via Settings.</li>
          </ul>
        </Section>

        <Section id="cookies" title="7. Cookies">
          <p>
            Copie Past-e uses minimal cookies and browser storage to provide
            core functionality:
          </p>
          <ul className="legal-list mt-4">
            <li>
              <strong className="text-foreground">Session storage:</strong>{" "}
              Temporary authentication state managed by Internet Identity.
            </li>
            <li>
              <strong className="text-foreground">Local storage:</strong> User
              preferences (e.g., onboarding completion status, extension
              detection flag) stored locally on your device only.
            </li>
          </ul>
          <p className="mt-4">
            We do not use third-party advertising cookies or tracking pixels.
            You can clear browser storage at any time through your browser
            settings.
          </p>
        </Section>

        <Section id="children" title="8. Children's Privacy">
          <p>
            Copie Past-e is not directed to children under the age of 13. We do
            not knowingly collect personal information from children under 13.
            If we become aware that we have collected personal information from
            a child under 13, we will take steps to delete that information as
            quickly as possible.
          </p>
          <p className="mt-4">
            If you are between 13 and 18 years of age, you may only use the
            service with the involvement and consent of a parent or legal
            guardian.
          </p>
        </Section>

        <Section id="changes" title="9. Changes to This Policy">
          <p>
            We may update this Privacy Policy periodically. When we make
            material changes, we will notify active users via an in-app
            notification at least 14 days before the changes take effect. The
            updated policy will be posted on this page with a revised "Last
            Updated" date.
          </p>
          <p className="mt-4">
            Your continued use of the service after any changes constitutes
            acceptance of the updated Privacy Policy.
          </p>
        </Section>

        <Section id="contact" title="10. Contact Us">
          <div className="border border-accent/30 bg-accent/5 rounded p-4 font-mono text-xs text-accent">
            ⚠ PLACEHOLDER — Insert privacy officer contact information, business
            address, and designated email address for privacy requests (e.g.,
            privacy@copie-paste.app) before launch.
          </div>
          <p className="mt-4">
            For privacy concerns or data requests, use the in-app Help & Support
            button. We aim to respond to all privacy inquiries within 30
            business days.
          </p>
        </Section>

        {/* Footer navigation */}
        <div className="mt-12 pt-6 border-t border-border/40 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="font-mono text-[10px] text-muted-foreground">
            © {new Date().getFullYear()} Copie Past-e. All rights reserved.
          </p>
          <div className="flex gap-4">
            <a
              href="/privacy"
              className="font-mono text-[10px] text-primary uppercase tracking-widest"
            >
              Privacy Policy
            </a>
            <a
              href="/terms"
              className="font-mono text-[10px] text-muted-foreground hover:text-primary transition-smooth uppercase tracking-widest"
            >
              Terms of Service
            </a>
          </div>
        </div>
      </div>
    </Layout>
  );
}
