/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddImageArgs {
  'order' : bigint,
  'blob' : ExternalBlob,
  'listingId' : ListingId,
  'altText' : string,
}
export interface AdminNotification {
  'id' : bigint,
  'notifType' : string,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'message' : string,
  'priority' : string,
  'relatedId' : [] | [string],
  'relatedUser' : string,
  'targetAdminId' : [] | [string],
}
export interface AdminTierAction {
  'tierId' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'newExpirationDate' : bigint,
  'daysAdded' : bigint,
  'adminId' : Principal,
}
export interface AppError { 'code' : ErrorCode, 'message' : string }
export interface AppVersion {
  'id' : bigint,
  'versionLabel' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
  'settingsSnapshot' : SiteSettings,
  'isRollback' : boolean,
}
export interface AuditEntry {
  'action' : string,
  'timestamp' : bigint,
  'details' : [] | [string],
  'caller' : Principal,
}
export interface AuditLogEntry {
  'id' : bigint,
  'action' : string,
  'timestamp' : Timestamp,
  'details' : string,
  'adminId' : UserId,
  'targetUserId' : [] | [UserId],
}
export interface AutofillHealthStatus {
  'successRate' : number,
  'isHealthy' : boolean,
  'enabled' : boolean,
  'totalAttempts' : bigint,
  'lastTestResult' : [] | [string],
  'lastTestAt' : [] | [Timestamp],
  'totalSuccessful' : bigint,
  'activeSessions' : bigint,
  'platformName' : string,
}
export interface AutofillTestResult {
  'fieldsFailed' : Array<string>,
  'duration' : bigint,
  'platform' : string,
  'message' : string,
  'success' : boolean,
  'fieldsPrepped' : Array<string>,
}
export interface AutofillValidation {
  'valid' : boolean,
  'errors' : Array<string>,
  'warnings' : Array<string>,
  'platformReady' : boolean,
}
export interface BackupHistoryRecord {
  'id' : string,
  'downloadExpiresAt' : Timestamp,
  'userId' : UserId,
  'imageCount' : bigint,
  'exportedAt' : Timestamp,
  'downloadToken' : string,
  'listingCount' : bigint,
  'paymentIntentId' : string,
}
export interface BackupImageEntry {
  'originalUrl' : string,
  'filename' : string,
}
export interface BackupListingEntry {
  'id' : bigint,
  'title' : string,
  'favorited' : boolean,
  'subcategory' : [] | [string],
  'createdAt' : Timestamp,
  'description' : string,
  'sourceUrl' : [] | [string],
  'pinned' : boolean,
  'category' : [] | [string],
  'brand' : [] | [string],
  'price' : [] | [string],
  'typeModel' : [] | [string],
  'condition' : [] | [string],
  'images' : Array<BackupImageEntry>,
  'archivedAt' : [] | [Timestamp],
}
export interface BackupRecord {
  'id' : bigint,
  'status' : BackupStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'downloadUrl' : string,
  'fileSize' : bigint,
}
export type BackupStatus = { 'pending' : null } |
  { 'complete' : null } |
  { 'failed' : null };
export interface BulkGasDiscount {
  'minGasAmount' : bigint,
  'description' : string,
  'discountPercent' : bigint,
}
export interface CampaignResults {
  'totalListingsPublished' : bigint,
  'publishedAt' : [] | [bigint],
  'totalSales' : bigint,
  'totalListingsFailed' : bigint,
  'avgConversionRate' : [] | [number],
  'totalRevenue' : [] | [string],
  'avgViewsPerListing' : [] | [number],
  'totalListingsSucceeded' : bigint,
}
export interface ComponentMetrics {
  'successCount' : bigint,
  'uptime' : number,
  'errorCount' : bigint,
  'responseTime' : bigint,
}
export interface ComponentStatus {
  'status' : { 'warning' : null } |
    { 'healthy' : null } |
    { 'error' : null } |
    { 'offline' : null },
  'metrics' : ComponentMetrics,
  'name' : string,
  'lastCheck' : Timestamp,
  'message' : string,
  'category' : string,
}
export type Condition = { 'new' : null } |
  { 'fair' : null } |
  { 'good' : null } |
  { 'poor' : null } |
  { 'likeNew' : null } |
  { 'unknown' : null };
export interface ConfigEntry {
  'key' : string,
  'value' : string,
  'encrypted' : boolean,
  'updatedAt' : Timestamp,
  'updatedBy' : string,
  'category' : string,
}
export interface CreateListingArgs {
  'mecariCondition' : [] | [Condition],
  'tierLevel' : [] | [bigint],
  'title' : string,
  'fbLocalPickup' : [] | [boolean],
  'description' : string,
  'platform' : [] | [Platform__1],
  'sourceUrl' : [] | [string],
  'mecariDeliveryDays' : [] | [bigint],
  'fbShipping' : [] | [boolean],
  'fbCondition' : [] | [Condition],
  'category' : [] | [string],
  'mecariShippingType' : [] | [string],
  'mecariBrand' : [] | [string],
  'price' : [] | [string],
}
export interface CreateMasterListingArgs {
  'title' : string,
  'tags' : Array<string>,
  'description' : string,
  'category' : [] | [string],
  'price' : [] | [string],
  'photos' : Array<Uint8Array>,
}
export interface CreateVersionArgs {
  'versionLabel' : string,
  'description' : string,
}
export interface CrossListingCampaign {
  'id' : string,
  'status' : { 'active' : null } |
    { 'completed' : null } |
    { 'draft' : null } |
    { 'failed' : null },
  'listings' : Array<string>,
  'userId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'results' : CampaignResults,
  'targetPlatforms' : Array<string>,
}
export interface DepopFields {
  'title' : string,
  'color' : [] | [string],
  'size' : [] | [string],
  'description' : string,
  'category' : [] | [string],
  'brand' : [] | [string],
  'price' : [] | [string],
  'photos' : Array<Uint8Array>,
  'condition' : [] | [string],
}
export interface DiscountCode {
  'id' : bigint,
  'active' : boolean,
  'discountValue' : number,
  'code' : string,
  'discountType' : DiscountType,
  'usageCount' : bigint,
  'expirationDate' : bigint,
  'tierRestriction' : [] | [bigint],
  'maxUses' : bigint,
}
export type DiscountType = { 'fixedUSD' : null } |
  { 'percentage' : null };
export type DraftListingId = bigint;
export type DraftStatus = { 'preparing' : null } |
  { 'unsaved' : null } |
  { 'saved' : null } |
  { 'ready' : null } |
  { 'posted' : null };
export interface EbayFields {
  'title' : string,
  'description' : string,
  'shippingCost' : [] | [string],
  'quantity' : bigint,
  'category' : [] | [string],
  'price' : [] | [string],
  'photos' : Array<Uint8Array>,
  'condition' : [] | [FacebookCondition],
}
export type ErrorCode = { 'platformNotSupported' : null } |
  { 'invalidInput' : null } |
  { 'duplicateEntry' : null } |
  { 'systemError' : null } |
  { 'notFound' : null } |
  { 'quotaExceeded' : null } |
  { 'unauthorized' : null } |
  { 'draftNotFound' : null };
export interface EtsyFields {
  'whoMade' : [] | [string],
  'title' : string,
  'tags' : Array<string>,
  'description' : string,
  'whenMade' : [] | [string],
  'materials' : Array<string>,
  'category' : [] | [string],
  'price' : [] | [string],
  'photos' : Array<Uint8Array>,
  'isSupply' : boolean,
}
export interface ExtensionListingData {
  'mecariCondition' : [] | [ItemCondition],
  'totalImageSize' : [] | [bigint],
  'title' : string,
  'fbLocalPickup' : [] | [boolean],
  'imageUrls' : Array<string>,
  'mecariCategory' : [] | [string],
  'description' : [] | [string],
  'platform' : Platform,
  'sourceUrl' : [] | [string],
  'mecariDeliveryDays' : [] | [bigint],
  'fbShipping' : [] | [boolean],
  'fbCondition' : [] | [ItemCondition],
  'offerUpCondition' : [] | [ItemCondition],
  'mecariShippingType' : [] | [string],
  'mecariBrand' : [] | [string],
  'price' : [] | [string],
  'fbCategory' : [] | [string],
  'imageFileTypes' : Array<string>,
  'offerUpCategory' : [] | [string],
}
export interface ExtensionUpdateCheck {
  'needsUpdate' : boolean,
  'downloadUrl' : string,
  'releaseNotes' : string,
  'currentVersion' : string,
  'latestVersion' : string,
  'buildNumber' : bigint,
  'isForceUpdate' : boolean,
}
export interface ExtensionVersion {
  'downloadUrl' : string,
  'releaseNotes' : string,
  'version' : string,
  'releasedAt' : Timestamp,
  'supportedPlatforms' : Array<string>,
  'buildNumber' : bigint,
  'isForceUpdate' : boolean,
}
export type ExternalBlob = Uint8Array;
export type FacebookCondition = { 'new' : null } |
  { 'fair' : null } |
  { 'good' : null } |
  { 'poor' : null } |
  { 'likeNew' : null };
export interface FacebookFields {
  'title' : string,
  'localPickup' : boolean,
  'shipping' : boolean,
  'description' : string,
  'category' : [] | [string],
  'price' : [] | [string],
  'photos' : Array<Uint8Array>,
  'condition' : [] | [FacebookCondition],
}
export interface FbCredentials { 'appId' : string, 'accessToken' : string }
export interface FbListing {
  'id' : string,
  'title' : string,
  'imageUrls' : Array<string>,
  'description' : [] | [string],
  'category' : [] | [string],
  'price' : [] | [string],
}
export interface FieldMapping {
  'weight' : [] | [string],
  'title' : string,
  'condition5Scale' : [] | [string],
  'localPickup' : [] | [boolean],
  'color' : [] | [string],
  'size' : [] | [string],
  'shipping' : [] | [boolean],
  'deliveryDays' : [] | [bigint],
  'description' : string,
  'shippingCost' : [] | [string],
  'shippingType' : [] | [string],
  'category' : [] | [string],
  'brand' : [] | [string],
  'dimensions' : [] | [string],
  'condition' : [] | [string],
}
export interface GasPackage {
  'gasAmount' : bigint,
  'name' : string,
  'stripeProductId' : string,
  'priceUSD' : number,
  'packageId' : bigint,
}
export interface GasPurchase {
  'id' : bigint,
  'status' : GasPurchaseStatus,
  'userId' : UserId,
  'gasAmount' : bigint,
  'createdAt' : Timestamp,
  'stripePaymentIntentId' : string,
  'priceUSD' : number,
}
export type GasPurchaseStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface GasWallet {
  'userId' : UserId,
  'autoRenewal' : boolean,
  'updatedAt' : Timestamp,
  'autoRenewalTierId' : bigint,
  'gasBalance' : bigint,
}
export type GetProfileResult = { 'ok' : UserProfile } |
  { 'err' : string };
export interface HealthStatus {
  'status' : string,
  'backupCount' : bigint,
  'keysConfigured' : boolean,
  'lastBackupAt' : Timestamp,
  'criticalKeysPresent' : boolean,
}
export interface Image {
  'id' : ImageId,
  'order' : bigint,
  'blob' : ExternalBlob,
  'listingId' : ListingId,
  'altText' : string,
}
export type ImageId = bigint;
export interface InAppNotification {
  'id' : bigint,
  'title' : string,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'message' : string,
}
export interface IntegrationStatus {
  'configPresent' : boolean,
  'name' : string,
  'errorMessage' : [] | [string],
  'lastTestResult' : [] | [boolean],
  'lastTestAt' : [] | [Timestamp],
  'connected' : boolean,
}
export type ItemCondition = { 'new' : null } |
  { 'fair' : null } |
  { 'good' : null } |
  { 'poor' : null } |
  { 'likeNew' : null } |
  { 'unknown' : null };
export interface Listing {
  'id' : ListingId,
  'mecariCondition' : [] | [Condition],
  'status' : ListingStatus,
  'tierLevel' : bigint,
  'title' : string,
  'fbLocalPickup' : [] | [boolean],
  'favorited' : boolean,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'description' : string,
  'platform' : [] | [Platform__1],
  'sourceUrl' : [] | [string],
  'mecariDeliveryDays' : [] | [bigint],
  'pinned' : boolean,
  'expirationDate' : Timestamp,
  'fbShipping' : [] | [boolean],
  'fbCondition' : [] | [Condition],
  'archivedManually' : boolean,
  'pinnedAt' : [] | [Timestamp],
  'restoredAt' : [] | [Timestamp],
  'category' : [] | [string],
  'mecariShippingType' : [] | [string],
  'brand' : [] | [string],
  'mecariBrand' : [] | [string],
  'price' : [] | [string],
  'condition' : [] | [string],
  'archivedAt' : [] | [Timestamp],
}
export type ListingId = bigint;
export interface ListingMetrics {
  'viewsPerPlatform' : Array<[string, bigint]>,
  'totalOffers' : bigint,
  'offersPerPlatform' : Array<[string, bigint]>,
  'totalViews' : bigint,
  'salesPerPlatform' : Array<[string, bigint]>,
  'totalLikes' : bigint,
  'totalSales' : bigint,
  'conversionRate' : [] | [number],
  'avgTimeToSale' : [] | [bigint],
  'likesPerPlatform' : Array<[string, bigint]>,
}
export interface ListingSnapshot {
  'title' : string,
  'favorited' : boolean,
  'description' : string,
  'pinned' : boolean,
  'category' : [] | [string],
  'price' : [] | [string],
}
export type ListingStatus = { 'active' : null } |
  { 'archived' : null };
export type ListingStatus__1 = { 'active' : null } |
  { 'pending' : null } |
  { 'sold' : null } |
  { 'draft' : null } |
  { 'archived' : null };
export type ListingStatus__2 = { 'active' : null } |
  { 'draft' : null } |
  { 'archived' : null };
export interface LoyaltyStatus {
  'rewardClaimedForTiers' : Array<TierName>,
  'currentTier' : TierName,
  'refuelCount' : bigint,
}
export type ManualPostAction = { 'submitted' : null } |
  { 'edited' : null } |
  { 'error' : null } |
  { 'saved' : null } |
  { 'drafted' : null };
export interface ManualPostEntry {
  'action' : ManualPostAction,
  'message' : string,
  'remoteUrl' : [] | [string],
  'timestamp' : bigint,
}
export type MarkReadResult = { 'ok' : null } |
  { 'err' : string };
export type MarketplaceSource = { 'facebookMarketplace' : null } |
  { 'offerUp' : null } |
  { 'unknown' : null };
export interface MasterListing {
  'id' : string,
  'status' : ListingStatus__2,
  'title' : string,
  'platformDrafts' : Array<PlatformListingDraft>,
  'userId' : Principal,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'auditLog' : Array<AuditEntry>,
  'updatedAt' : bigint,
  'pinned' : boolean,
  'expirationDate' : [] | [bigint],
  'pinnedAt' : [] | [bigint],
  'category' : [] | [string],
  'archivedReason' : [] | [string],
  'price' : [] | [string],
  'photos' : Array<Uint8Array>,
  'favoriteCount' : bigint,
  'archivedAt' : [] | [bigint],
}
export type MecariCondition5Scale = { 'new' : null } |
  { 'fair' : null } |
  { 'good' : null } |
  { 'poor' : null } |
  { 'likeNew' : null };
export interface MecariFields {
  'title' : string,
  'deliveryDays' : [] | [bigint],
  'description' : string,
  'shippingType' : [] | [
    { 'normal' : null } |
      { 'fast' : null } |
      { 'sameDay' : null }
  ],
  'category' : [] | [string],
  'brand' : string,
  'price' : [] | [string],
  'photos' : Array<Uint8Array>,
  'condition' : [] | [MecariCondition5Scale],
}
export interface MonitoringLogEntry {
  'component' : string,
  'level' : string,
  'message' : string,
  'timestamp' : bigint,
  'cyclesAvailable' : bigint,
}
export type NotificationType = { 'refuelSuccess' : null } |
  { 'lowFuelWarning' : null } |
  { 'subscriptionExpiry' : null } |
  { 'listingDeletionWarning' : null } |
  { 'subscriptionRenewed' : null } |
  { 'subscriptionCancelled' : null } |
  { 'adminAnnouncement' : null } |
  { 'listingArchived' : null } |
  { 'paymentFailed' : null };
export interface OcrFailureEntry {
  'imageHash' : string,
  'errorType' : string,
  'userPrincipal' : string,
  'timestamp' : bigint,
  'errorReason' : string,
}
export interface OcrResult {
  'title' : string,
  'description' : string,
  'category' : string,
  'brand' : string,
  'price' : string,
  'condition' : string,
}
export interface ParsedListingResult {
  'title' : [] | [string],
  'description' : [] | [string],
  'category' : [] | [string],
  'price' : [] | [string],
}
export interface PaymentBannerState {
  'expiresAt' : [] | [bigint],
  'bannerType' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'message' : string,
}
export interface PaymentConfig {
  'stripeProPriceId' : [] | [string],
  'stripeBackupPriceId' : [] | [string],
  'paypalMode' : string,
  'stripeSecretKey' : [] | [string],
  'stripeWebhookSecretLive' : [] | [string],
  'stripeWebhookSecretTest' : [] | [string],
  'stripePublishableKey' : [] | [string],
  'stripeMode' : string,
  'stripeMaxPriceId' : [] | [string],
  'paypalClientId' : [] | [string],
  'paypalClientSecret' : [] | [string],
  'stripeWebhookSecret' : [] | [string],
  'stripeWalkerPriceId' : [] | [string],
}
export type PaymentMethod = { 'stripe' : null } |
  { 'crypto' : null } |
  { 'paypal' : null };
export interface PaymentRecord {
  'id' : bigint,
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'tierId' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'stripePaymentIntentId' : [] | [string],
  'amountUSD' : number,
  'externalOrderId' : [] | [string],
}
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type Platform = { 'facebookMarketplace' : null } |
  { 'offerUp' : null } |
  { 'unknown' : null } |
  { 'mecari' : null };
export interface PlatformAutofillConfig {
  'fbPrefillDescription' : boolean,
  'fbAutoClickLocalPickup' : boolean,
  'mecariPrefillDescription' : boolean,
  'lastUpdated' : Timestamp,
  'mecariPrefillCondition' : boolean,
  'enabled' : boolean,
  'updatedBy' : string,
  'mecariAutoSelectDeliveryDays' : boolean,
  'mecariAutoSelectShipping' : boolean,
  'mecariPrefillBrand' : boolean,
  'fbPrefillPrice' : boolean,
  'mecariPrefillPrice' : boolean,
  'mecariShippingType' : [] | [string],
  'fbPrefillCondition' : boolean,
  'fbAutoClickShipping' : boolean,
  'mecariDeliveryDaysValue' : [] | [bigint],
  'fbPrefillCategory' : boolean,
  'fbPrefillTitle' : boolean,
  'platformName' : string,
  'mecariPrefillCategory' : boolean,
  'mecariPrefillTitle' : boolean,
}
export interface PlatformCapabilities {
  'supportsAutoSync' : boolean,
  'supportsCondition' : boolean,
  'maxPhotos' : bigint,
  'maxTitleLength' : bigint,
  'supportsShipping' : boolean,
  'priceFormat' : string,
  'supportedCategories' : Array<string>,
  'apiAvailable' : boolean,
  'maxDescriptionLength' : bigint,
  'name' : string,
  'supportsBulkListing' : boolean,
  'supportsLocalPickup' : boolean,
  'requiresCategory' : boolean,
  'supportsBrand' : boolean,
}
export type PlatformFields = { 'poshmark' : PoshmarkFields } |
  { 'ebay' : EbayFields } |
  { 'etsy' : EtsyFields } |
  { 'facebook' : FacebookFields } |
  { 'depop' : DepopFields } |
  { 'mecari' : MecariFields };
export interface PlatformListingDraft {
  'status' : DraftStatus,
  'lastEditedAt' : bigint,
  'createdAt' : bigint,
  'validationErrors' : Array<{ 'field' : string, 'error' : string }>,
  'platform' : Platform__2,
  'manualPostingLog' : Array<ManualPostEntry>,
  'isValid' : boolean,
  'platformFields' : PlatformFields,
  'draftId' : string,
  'completenessPercent' : bigint,
}
export interface PlatformTarget {
  'status' : RemoteListingStatus,
  'listingId' : [] | [string],
  'publishedAt' : [] | [bigint],
  'customPrice' : [] | [string],
  'platform' : string,
  'enabled' : boolean,
  'syncedAt' : [] | [bigint],
  'mappedFields' : FieldMapping,
  'customCategory' : [] | [string],
}
export type Platform__1 = { 'facebook' : null } |
  { 'offerUp' : null } |
  { 'unknown' : null } |
  { 'mecari' : null };
export type Platform__2 = { 'poshmark' : null } |
  { 'ebay' : null } |
  { 'etsy' : null } |
  { 'facebook' : null } |
  { 'depop' : null } |
  { 'mecari' : null };
export interface PoshmarkFields {
  'title' : string,
  'color' : [] | [string],
  'size' : [] | [string],
  'description' : string,
  'category' : [] | [string],
  'brand' : [] | [string],
  'department' : [] | [string],
  'price' : [] | [string],
  'photos' : Array<Uint8Array>,
  'condition' : [] | [string],
}
export interface PricingRules {
  'maxPrice' : [] | [string],
  'priceAdjustmentPerPlatform' : Array<[string, string]>,
  'minPrice' : [] | [string],
  'priceMarkupPercent' : [] | [number],
  'basePrice' : string,
  'autoRepricing' : boolean,
}
export interface PublishSchedule {
  'scheduledTime' : [] | [bigint],
  'scheduleType' : { 'scheduled' : null } |
    { 'batch' : null } |
    { 'immediate' : null },
  'batchNumber' : [] | [bigint],
  'itemsPerBatch' : [] | [bigint],
}
export interface RefuelEntry { 'tierAtRefuel' : TierName, 'date' : bigint }
export type RemoteListingStatus = { 'scheduled' : null } |
  { 'active' : null } |
  { 'sold' : null } |
  { 'error' : null } |
  { 'syncing' : null } |
  { 'delisted' : null };
export type ResendResult = {
    'ok' : { 'resendCount' : bigint, 'cooldownSecondsRemaining' : bigint }
  } |
  { 'err' : string };
export interface RestoreResult {
  'errorMessage' : [] | [string],
  'preSaveBackupId' : string,
  'usersRestored' : bigint,
  'listingsRestored' : bigint,
  'success' : boolean,
}
export interface SavePlatformDraftArgs {
  'platform' : Platform__2,
  'platformFields' : PlatformFields,
  'photos' : Array<Uint8Array>,
}
export type ScrapeResult = { 'ok' : ScrapedListing } |
  { 'err' : string };
export interface ScrapedListing {
  'title' : [] | [string],
  'imageUrls' : Array<string>,
  'source' : MarketplaceSource,
  'description' : [] | [string],
  'sourceUrl' : string,
  'category' : [] | [string],
  'price' : [] | [string],
}
export type SetUsernameResult = { 'ok' : UserProfile } |
  { 'err' : string };
export interface SiteAnalytics {
  'totalListings' : bigint,
  'avgImagesPerListing' : number,
  'totalArchivedListings' : bigint,
  'totalUsers' : bigint,
  'totalImages' : bigint,
  'paymentRevenue' : number,
  'totalActiveListings' : bigint,
  'avgListingsPerUser' : number,
}
export interface SiteSettings {
  'maxSessionDurationMinutes' : bigint,
  'appName' : string,
  'primaryColor' : string,
  'contentModerationEnabled' : boolean,
  'createdAt' : Timestamp,
  'accentColor' : string,
  'updatedAt' : Timestamp,
  'copyButtonsEnabled' : boolean,
  'maxRequestsPerMinute' : bigint,
  'maxConcurrentSessions' : bigint,
  'allowedOrigins' : string,
  'uploadEnabled' : boolean,
  'maxUploadsPerHour' : bigint,
}
export interface SupportTicket {
  'id' : bigint,
  'status' : string,
  'adminReply' : [] | [string],
  'username' : string,
  'subject' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'repliedAt' : [] | [Timestamp],
  'message' : string,
  'attachmentUrls' : [] | [Array<string>],
}
export interface SystemDiagnostics {
  'recommendations' : Array<string>,
  'criticalFailures' : Array<string>,
  'components' : Array<ComponentStatus>,
  'issues' : Array<SystemIssue>,
  'timestamp' : Timestamp,
  'overallStatus' : { 'warning' : null } |
    { 'healthy' : null } |
    { 'critical' : null },
}
export interface SystemIssue {
  'id' : string,
  'resolved' : boolean,
  'title' : string,
  'description' : string,
  'affectedComponent' : string,
  'suggestedFix' : string,
  'severity' : { 'warning' : null } |
    { 'info' : null } |
    { 'error' : null } |
    { 'critical' : null },
  'discoveredAt' : Timestamp,
}
export interface TierConfig {
  'durationDays' : bigint,
  'tierId' : bigint,
  'name' : string,
  'stripeProductId' : [] | [string],
  'priceUSD' : number,
}
export type TierName = string;
export type Timestamp = bigint;
export interface UniversalListing {
  'id' : string,
  'status' : ListingStatus__1,
  'soldOnPlatforms' : Array<string>,
  'title' : string,
  'publishSchedule' : [] | [PublishSchedule],
  'metrics' : ListingMetrics,
  'userId' : Principal,
  'createdAt' : bigint,
  'publishedAt' : [] | [bigint],
  'description' : string,
  'pricingRules' : PricingRules,
  'quantitySold' : bigint,
  'quantity' : bigint,
  'category' : [] | [string],
  'brand' : [] | [string],
  'lastSyncAt' : [] | [bigint],
  'price' : [] | [string],
  'photos' : Array<Uint8Array>,
  'targetPlatforms' : Array<PlatformTarget>,
  'condition' : string,
}
export interface UpdateListingArgs {
  'id' : ListingId,
  'mecariCondition' : [] | [Condition],
  'tierLevel' : [] | [bigint],
  'title' : string,
  'fbLocalPickup' : [] | [boolean],
  'description' : string,
  'platform' : [] | [Platform__1],
  'mecariDeliveryDays' : [] | [bigint],
  'fbShipping' : [] | [boolean],
  'fbCondition' : [] | [Condition],
  'category' : [] | [string],
  'mecariShippingType' : [] | [string],
  'mecariBrand' : [] | [string],
  'price' : [] | [string],
}
export interface UpdateMasterListingArgs {
  'title' : [] | [string],
  'tags' : [] | [Array<string>],
  'description' : [] | [string],
  'category' : [] | [string],
  'price' : [] | [string],
}
export interface UpdateProfileArgs {
  'displayName' : [] | [string],
  'email' : [] | [string],
  'phoneNumber' : [] | [string],
}
export type UpdateProfileResult = { 'ok' : UserProfile } |
  { 'err' : string };
export interface UpdateSettingsArgs {
  'maxSessionDurationMinutes' : bigint,
  'appName' : string,
  'primaryColor' : string,
  'contentModerationEnabled' : boolean,
  'accentColor' : string,
  'copyButtonsEnabled' : boolean,
  'maxRequestsPerMinute' : bigint,
  'maxConcurrentSessions' : bigint,
  'allowedOrigins' : string,
  'uploadEnabled' : boolean,
  'maxUploadsPerHour' : bigint,
}
export interface UserCleanupSummary {
  'hasExpiredListings' : boolean,
  'userId' : Principal,
  'email' : string,
  'archivedListingCount' : bigint,
  'oldestActiveExpirationDate' : [] | [Timestamp],
  'activeListingCount' : bigint,
}
export type UserId = Principal;
export interface UserProfile {
  'fbWebhookToken' : [] | [string],
  'emailVerified' : boolean,
  'username' : string,
  'displayName' : [] | [string],
  'userId' : UserId,
  'createdAt' : Timestamp,
  'role' : string,
  'email' : string,
  'fbAppId' : [] | [string],
  'fbAccessToken' : [] | [string],
  'updatedAt' : Timestamp,
  'stripeCustomerId' : [] | [string],
  'phoneNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'lastLoginDate' : [] | [Timestamp],
  'userId' : string,
  'role' : string,
  'imageCount' : bigint,
  'registrationDate' : Timestamp,
  'listingCount' : bigint,
}
export interface UserTierSubscription {
  'stripeSubscriptionId' : [] | [string],
  'userId' : Principal,
  'tier' : bigint,
  'autoRenewal' : boolean,
  'updatedAt' : bigint,
  'expirationDate' : bigint,
}
export interface VerificationRecord {
  'status' : VerificationStatus,
  'token' : string,
  'expiresAt' : Timestamp,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'resendCount' : bigint,
  'email' : string,
  'lastResendAt' : [] | [Timestamp],
}
export type VerificationStatus = { 'verified' : null } |
  { 'expired' : null } |
  { 'pending' : null };
export type VerifyEmailResult = { 'ok' : null } |
  { 'err' : string };
export interface VersionBackup {
  'id' : string,
  'versionLabel' : string,
  'createdAt' : Timestamp,
  'createdBy' : string,
  'isStable' : boolean,
  'backupData' : string,
  'backupType' : string,
  'notes' : [] | [string],
}
export interface VersionBackupSummary {
  'id' : string,
  'versionLabel' : string,
  'createdAt' : Timestamp,
  'createdBy' : string,
  'isStable' : boolean,
  'backupType' : string,
  'notes' : [] | [string],
  'configCount' : bigint,
  'sizeKb' : bigint,
  'listingCount' : bigint,
  'userCount' : bigint,
}
export interface ZipRestoreResult {
  'errorMessage' : [] | [string],
  'listingsRestored' : bigint,
  'success' : boolean,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addImage' : ActorMethod<[AddImageArgs], Image>,
  'adminCreateBackupNow' : ActorMethod<
    [],
    { 'ok' : { 'backupId' : string, 'createdAt' : bigint } } |
      { 'err' : string }
  >,
  'adminCreateDiscountCode' : ActorMethod<
    [string, DiscountType, number, bigint, bigint, [] | [bigint]],
    DiscountCode
  >,
  'adminDeactivateDiscountCode' : ActorMethod<[bigint], undefined>,
  'adminDeleteUser' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminExtendUserTier' : ActorMethod<
    [UserId, bigint, bigint],
    UserTierSubscription
  >,
  'adminExtendUserTierByUsername' : ActorMethod<
    [string, bigint, bigint],
    { 'ok' : UserTierSubscription } |
      { 'err' : string }
  >,
  'adminForceResaveStripeConfig' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminGetGeminiConfig' : ActorMethod<
    [],
    { 'model' : string, 'configured' : boolean }
  >,
  'adminGetPaymentConfig' : ActorMethod<[], PaymentConfig>,
  'adminGetUserIdByUsername' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminGetUserSubscription' : ActorMethod<
    [UserId],
    [] | [UserTierSubscription]
  >,
  'adminListDiscountCodes' : ActorMethod<[], Array<DiscountCode>>,
  'adminListExtensionVersions' : ActorMethod<[], Array<ExtensionVersion>>,
  'adminListPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'adminListProfiles' : ActorMethod<[], Array<UserProfile>>,
  'adminListSubscriptions' : ActorMethod<[], Array<UserTierSubscription>>,
  'adminListTierActions' : ActorMethod<[], Array<AdminTierAction>>,
  'adminLockBackupPermanent' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminResetAllUserSubscriptions' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminResetUserSubscription' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSaveGeminiConfig' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSavePaymentConfig' : ActorMethod<
    [PaymentConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSendAnnouncement' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetExtensionVersion' : ActorMethod<
    [string, bigint, string, string, boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSetGeminiKey' : ActorMethod<[string], undefined>,
  'adminSetMaintenanceMode' : ActorMethod<[boolean, string], undefined>,
  'adminSetSiteBaseUrl' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetStripeKeys' : ActorMethod<[string, string, string], undefined>,
  'adminSetStripePrices' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'adminTestAndVerifyStripeConfig' : ActorMethod<
    [],
    {
      'testPassed' : boolean,
      'modeCorrect' : boolean,
      'pubKeyPresent' : boolean,
      'secretKeyPresent' : boolean,
      'message' : string,
      'configValid' : boolean,
    }
  >,
  'adminTestGeminiConnection' : ActorMethod<
    [],
    { 'message' : string, 'success' : boolean }
  >,
  'adminTestPaypalConnection' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminTestStripeConnection' : ActorMethod<
    [],
    { 'message' : string, 'success' : boolean }
  >,
  'adminUpsertTier' : ActorMethod<[TierConfig], undefined>,
  'archiveListing' : ActorMethod<[ListingId], Listing>,
  'archiveMasterListing' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : string } |
      { 'err' : AppError }
  >,
  'assertConfig' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[string, string], undefined>,
  'checkAndCreateLowFuelNotification' : ActorMethod<
    [number, Timestamp],
    [] | [InAppNotification]
  >,
  'checkExtensionUpdateStatus' : ActorMethod<[string], ExtensionUpdateCheck>,
  'claimLoyaltyReward' : ActorMethod<
    [TierName],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'clearPendingSession' : ActorMethod<[], undefined>,
  'closeSupportTicket' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'confirmCryptoPayment' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'confirmGasPurchase' : ActorMethod<
    [bigint],
    { 'ok' : GasWallet } |
      { 'err' : string }
  >,
  'confirmPayPalPayment' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'confirmSmartBackupPayment' : ActorMethod<
    [bigint, string, bigint, bigint],
    { 'ok' : BackupHistoryRecord } |
      { 'err' : string }
  >,
  'confirmStripePayment' : ActorMethod<[bigint, string], undefined>,
  'createAdaptiveVersionSnapshot' : ActorMethod<[], [] | [VersionBackup]>,
  'createBackupRecord' : ActorMethod<[bigint], BackupRecord>,
  'createBroadcastNotification' : ActorMethod<
    [string, string, string, string, [] | [string]],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'createListing' : ActorMethod<[CreateListingArgs], Listing>,
  'createMasterListing' : ActorMethod<
    [CreateMasterListingArgs],
    { 'ok' : string } |
      { 'err' : AppError }
  >,
  'createStripeCheckoutSession' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Returns a lightweight system health snapshot: cycles, heap, log count,
   * / and the 20 most recent structured log entries from the monitoring ring buffer.
   */
  'createStripePortalSession' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createUniversalListing' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      string,
      [] | [string],
      bigint,
      Array<string>,
      {
        'platformPrices' : Array<[string, string]>,
        'priceMarkupPercent' : [] | [number],
        'basePrice' : string,
        'autoRepricing' : boolean,
      },
      [] | [
        {
          'scheduledTime' : [] | [bigint],
          'scheduleType' : { 'scheduled' : null } |
            { 'batch' : null } |
            { 'immediate' : null },
          'batchSize' : [] | [bigint],
        }
      ],
      {
        'facebook' : [] | [{ 'localPickup' : boolean, 'shipping' : boolean }],
        'mecari' : [] | [{ 'deliveryDays' : bigint, 'shippingType' : string }],
      },
    ],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createVersion' : ActorMethod<[CreateVersionArgs], AppVersion>,
  'createVersionBackup' : ActorMethod<
    [boolean, [] | [string]],
    { 'ok' : VersionBackup } |
      { 'err' : string }
  >,
  'debugCheckStripeKeyLength' : ActorMethod<[], bigint>,
  'debugConfigHealthReport' : ActorMethod<
    [],
    {
      'status' : string,
      'allCriticalKeysPresent' : boolean,
      'siteBaseUrlSet' : string,
      'stripePublishableKeyLength' : bigint,
      'geminiKeyLength' : bigint,
      'stripSecretKeyLength' : bigint,
      'stripeModeSet' : string,
    }
  >,
  'deleteBackup' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'deleteBackupRecord' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteConfig' : ActorMethod<[string], undefined>,
  'deleteListing' : ActorMethod<[ListingId], undefined>,
  'detectMarketplaceSource' : ActorMethod<[string], MarketplaceSource>,
  'dismissPaymentBanner' : ActorMethod<[], undefined>,
  'downloadDataSnapshot' : ActorMethod<
    [string],
    [] | [
      {
        'metadata' : {
          'created' : Timestamp,
          'size' : bigint,
          'backupType' : string,
        },
        'data' : string,
      }
    ]
  >,
  'downloadVersionBackupAsJson' : ActorMethod<
    [string],
    [] | [
      {
        'data' : string,
        'size' : bigint,
        'filename' : string,
        'backupType' : string,
        'timestamp' : Timestamp,
      }
    ]
  >,
  'exportAllUsersData' : ActorMethod<
    [],
    { 'imageUrls' : Array<string>, 'jsonData' : string }
  >,
  'exportSystemReport' : ActorMethod<
    [],
    {
      'issuesJson' : string,
      'componentsJson' : string,
      'recommendationsJson' : string,
      'timestamp' : Timestamp,
      'overallStatus' : string,
    }
  >,
  'exportUserData' : ActorMethod<
    [string],
    [] | [{ 'imageUrls' : Array<string>, 'jsonData' : string }]
  >,
  'exportVersionBackupAsJson' : ActorMethod<[string], [] | [string]>,
  'failGasPurchase' : ActorMethod<[bigint], undefined>,
  'failStripePayment' : ActorMethod<[bigint], undefined>,
  'generateBackupData' : ActorMethod<[], Array<ListingSnapshot>>,
  'generateFullBackupEntries' : ActorMethod<
    [Array<[bigint, Array<string>]>],
    Array<BackupListingEntry>
  >,
  'generateWebhookToken' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getAdaptiveBackupSchedule' : ActorMethod<
    [],
    { 'intervalHours' : bigint, 'nextBackupAt' : bigint, 'userCount' : bigint }
  >,
  'getAdminSettings' : ActorMethod<[], SiteSettings>,
  'getAllAutofillConfigs' : ActorMethod<[], Array<PlatformAutofillConfig>>,
  'getAllConfig' : ActorMethod<[], Array<ConfigEntry>>,
  'getAllPlatformCapabilities' : ActorMethod<[], Array<PlatformCapabilities>>,
  'getAuditLog' : ActorMethod<[], Array<AuditLogEntry>>,
  'getAutofillConfig' : ActorMethod<[string], [] | [PlatformAutofillConfig]>,
  'getAutofillHealthStatus' : ActorMethod<[], Array<AutofillHealthStatus>>,
  'getBackupDownloadInfo' : ActorMethod<[string], [] | [BackupHistoryRecord]>,
  'getBackupHistory' : ActorMethod<[], Array<BackupHistoryRecord>>,
  'getBulkGasDiscounts' : ActorMethod<[], Array<BulkGasDiscount>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampaignResults' : ActorMethod<[string], [] | [CrossListingCampaign]>,
  'getCanisterCyclesBalance' : ActorMethod<[], bigint>,
  'getCleanupSummaries' : ActorMethod<[], Array<UserCleanupSummary>>,
  'getConfig' : ActorMethod<[string], [] | [string]>,
  'getFbListings' : ActorMethod<
    [],
    { 'ok' : Array<FbListing> } |
      { 'err' : string }
  >,
  'getGasPackages' : ActorMethod<[], Array<GasPackage>>,
  'getHealthStatus' : ActorMethod<[], HealthStatus>,
  'getIntegrationStatus' : ActorMethod<[], Array<IntegrationStatus>>,
  'getLatestExtensionVersion' : ActorMethod<[], [] | [ExtensionUpdateCheck]>,
  'getListing' : ActorMethod<[ListingId], [] | [Listing]>,
  'getListingsByPlatform' : ActorMethod<
    [Platform__2],
    { 'ok' : Array<MasterListing> } |
      { 'err' : AppError }
  >,
  'getLogCount' : ActorMethod<[], bigint>,
  'getLoyaltyStatus' : ActorMethod<[], LoyaltyStatus>,
  'getMaintenanceMode' : ActorMethod<
    [],
    { 'eta' : string, 'isActive' : boolean, 'message' : string }
  >,
  'getMasterListing' : ActorMethod<
    [string],
    { 'ok' : MasterListing } |
      { 'err' : AppError }
  >,
  'getMasterListingStats' : ActorMethod<
    [],
    { 'totalListings' : bigint, 'totalDrafts' : bigint, 'totalUsers' : bigint }
  >,
  'getMonitoringStatus' : ActorMethod<
    [],
    { 'heapSize' : bigint, 'logCount' : bigint, 'cyclesAvailable' : bigint }
  >,
  'getMyBackups' : ActorMethod<[], Array<BackupRecord>>,
  'getMyFbCredentials' : ActorMethod<[], [] | [FbCredentials]>,
  'getMyGasPurchases' : ActorMethod<[], Array<GasPurchase>>,
  'getMyGasWallet' : ActorMethod<[], { 'ok' : GasWallet } | { 'err' : string }>,
  'getMyPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'getMyProfile' : ActorMethod<[], GetProfileResult>,
  'getMySubscription' : ActorMethod<[], [] | [UserTierSubscription]>,
  'getMyWebhookToken' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'getOcrFailureLog' : ActorMethod<[bigint], Array<OcrFailureEntry>>,
  'getPaymentBanner' : ActorMethod<[], [] | [PaymentBannerState]>,
  'getPendingSession' : ActorMethod<
    [],
    [] | [{ 'tierId' : bigint, 'tierDays' : bigint, 'sessionId' : string }]
  >,
  'getPlatformCapabilities' : ActorMethod<
    [string],
    [] | [PlatformCapabilities]
  >,
  'getProfileByUsername' : ActorMethod<[string], [] | [UserProfile]>,
  'getPublicConfig' : ActorMethod<
    [],
    {
      'maintenanceMessage' : string,
      'mode' : string,
      'gasWalkerPriceId' : string,
      'maintenanceMode' : boolean,
      'gasLordPriceId' : string,
      'gasTravelerPriceId' : string,
      'publishableKey' : string,
      'siteBaseUrl' : string,
    }
  >,
  'getRecentLogs' : ActorMethod<[bigint], Array<MonitoringLogEntry>>,
  'getRefuelHistory' : ActorMethod<[], Array<RefuelEntry>>,
  'getRevenueStats' : ActorMethod<
    [],
    {
      'month' : bigint,
      'today' : bigint,
      'week' : bigint,
      'activeSubscribers' : bigint,
    }
  >,
  'getSiteAnalytics' : ActorMethod<[], SiteAnalytics>,
  'getSiteBaseUrl' : ActorMethod<[], string>,
  'getStripeHealthStatus' : ActorMethod<
    [],
    {
      'status' : string,
      'lastWebhookReceived' : [] | [bigint],
      'keysConfigured' : boolean,
      'webhookConfigured' : boolean,
    }
  >,
  'getStripePublicKey' : ActorMethod<[], { 'publishableKey' : string }>,
  'getSupportTicket' : ActorMethod<[bigint], [] | [SupportTicket]>,
  'getSystemDiagnostics' : ActorMethod<[], SystemDiagnostics>,
  'getSystemHealthStatus' : ActorMethod<
    [],
    {
      'stripe' : {
        'status' : string,
        'hasPublishableKey' : boolean,
        'lastWebhookAt' : [] | [bigint],
        'hasPriceIds' : boolean,
        'hasSecretKey' : boolean,
      },
      'signups' : { 'total' : bigint, 'lastSignupAt' : [] | [bigint] },
      'backup' : {
        'status' : string,
        'freshnessHours' : [] | [bigint],
        'backupCount' : bigint,
        'lastBackupAt' : [] | [bigint],
      },
      'database' : {
        'status' : string,
        'canReadConfig' : boolean,
        'canReadUsers' : boolean,
      },
      'gemini' : { 'status' : string, 'hasApiKey' : boolean },
      'maintenance' : { 'isActive' : boolean },
      'paypal' : { 'status' : string, 'isConfigured' : boolean },
    }
  >,
  /**
   * / Returns a lightweight system health snapshot: cycles, heap, log count,
   * / and the 20 most recent structured log entries from the monitoring ring buffer.
   */
  'getSystemStatus' : ActorMethod<
    [],
    {
      'heapSize' : bigint,
      'logCount' : bigint,
      'recentLogs' : Array<MonitoringLogEntry>,
      'cycles' : bigint,
    }
  >,
  'getTier' : ActorMethod<[bigint], [] | [TierConfig]>,
  'getTiers' : ActorMethod<[], Array<TierConfig>>,
  'getUniversalListing' : ActorMethod<[string], [] | [UniversalListing]>,
  'getUnreadAdminNotificationCount' : ActorMethod<[], bigint>,
  'getUserMasterListings' : ActorMethod<
    [],
    { 'ok' : Array<MasterListing> } |
      { 'err' : AppError }
  >,
  'getUserNotifications' : ActorMethod<[], Array<InAppNotification>>,
  'getUserUniversalListings' : ActorMethod<[], Array<UniversalListing>>,
  'getVerificationStatus' : ActorMethod<[], [] | [VerificationRecord]>,
  'getVersionBackupIndex' : ActorMethod<
    [],
    {
      'latestSnapshot' : [] | [string],
      'manualSnapshots' : bigint,
      'totalSnapshots' : bigint,
      'autoSnapshots' : bigint,
      'oldestSnapshot' : [] | [string],
      'totalDataSize' : bigint,
    }
  >,
  'getVersionSnapshotList' : ActorMethod<[], Array<VersionBackupSummary>>,
  'initConfigFromPaymentConfig' : ActorMethod<[], undefined>,
  'initiateCryptoPayment' : ActorMethod<
    [bigint, [] | [string]],
    { 'ok' : PaymentRecord } |
      { 'err' : string }
  >,
  'initiateEmailVerification' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'initiateGasPurchase' : ActorMethod<
    [bigint, [] | [string]],
    {
        'ok' : {
          'gasAmount' : bigint,
          'purchaseRecordId' : bigint,
          'finalAmountUSD' : number,
          'stripeClientSecret' : string,
        }
      } |
      { 'err' : string }
  >,
  'initiatePayPalPayment' : ActorMethod<
    [bigint, [] | [string]],
    { 'ok' : PaymentRecord } |
      { 'err' : string }
  >,
  'initiateSmartBackup' : ActorMethod<
    [],
    {
      'paymentRecordId' : bigint,
      'backupPriceId' : [] | [string],
      'amountUSD' : number,
      'stripeClientSecret' : [] | [string],
    }
  >,
  'initiateTierUpgrade' : ActorMethod<
    [bigint, [] | [string]],
    {
      'tierDurationDays' : bigint,
      'discountApplied' : boolean,
      'paymentRecordId' : bigint,
      'finalAmountUSD' : number,
      'stripeClientSecret' : [] | [string],
    }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isConfigValid' : ActorMethod<[], boolean>,
  'listAdminNotifications' : ActorMethod<[], Array<AdminNotification>>,
  'listAllUsers' : ActorMethod<[], Array<UserSummary>>,
  'listBackupsForDownload' : ActorMethod<
    [],
    Array<
      {
        'id' : string,
        'created' : Timestamp,
        'size' : bigint,
        'filename' : string,
        'backupType' : string,
        'listingCount' : bigint,
        'userCount' : bigint,
      }
    >
  >,
  'listFavoritedListings' : ActorMethod<[], Array<Listing>>,
  'listImages' : ActorMethod<[ListingId], Array<Image>>,
  'listListings' : ActorMethod<[], Array<Listing>>,
  'listSupportTickets' : ActorMethod<[], Array<SupportTicket>>,
  'listVersionBackups' : ActorMethod<[], Array<VersionBackupSummary>>,
  'listVersionHistory' : ActorMethod<[], Array<AppVersion>>,
  'logAutofillSession' : ActorMethod<
    [string, bigint, bigint, Array<string>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'logEvent' : ActorMethod<[string, string, string], undefined>,
  'logManualPosting' : ActorMethod<
    [string, Platform__2, [] | [string]],
    { 'ok' : string } |
      { 'err' : AppError }
  >,
  'markAdminNotificationRead' : ActorMethod<[bigint], undefined>,
  'markAllAdminNotificationsRead' : ActorMethod<[], undefined>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markAsSOLD' : ActorMethod<[string], { 'ok' : string } | { 'err' : string }>,
  'markBackupAsStable' : ActorMethod<[string], boolean>,
  'markNotificationRead' : ActorMethod<[bigint], MarkReadResult>,
  'markUniversalListingReady' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'ocrScanImage' : ActorMethod<
    [string],
    { 'ok' : OcrResult } |
      { 'err' : string }
  >,
  'parsePastedText' : ActorMethod<[string], ParsedListingResult>,
  'permanentDeleteListing' : ActorMethod<
    [ListingId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'previewVersionRestoreSnapshot' : ActorMethod<
    [string],
    [] | [
      {
        'snapshotCreatedAt' : Timestamp,
        'createdBy' : string,
        'isManualBackup' : boolean,
        'notes' : [] | [string],
        'listingCount' : bigint,
        'userCount' : bigint,
      }
    ]
  >,
  'receiveExtensionData' : ActorMethod<
    [ExtensionListingData, string],
    { 'ok' : DraftListingId } |
      { 'err' : string } |
      {
        'validationError' : {
          'errors' : Array<string>,
          'platformReady' : boolean,
        }
      } |
      {
        'validationWarning' : {
          'warnings' : Array<string>,
          'draftId' : DraftListingId,
        }
      }
  >,
  'registerUserProfile' : ActorMethod<[string, string], SetUsernameResult>,
  'removeImage' : ActorMethod<[ImageId], undefined>,
  'replySupportTicket' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resendVerificationEmail' : ActorMethod<[string], ResendResult>,
  'restoreFromBackup' : ActorMethod<
    [Array<ListingSnapshot>],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'restoreFromJsonBlob' : ActorMethod<[string], RestoreResult>,
  'restoreFromVersionBackup' : ActorMethod<[string], RestoreResult>,
  'restoreFromVersionBackupWithSafety' : ActorMethod<[string], RestoreResult>,
  'restoreFromZipBackup' : ActorMethod<
    [Array<BackupListingEntry>],
    ZipRestoreResult
  >,
  'restoreListing' : ActorMethod<
    [ListingId],
    { 'ok' : Listing } |
      { 'err' : string }
  >,
  'restoreUserAccountFromBackup' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'rollbackToVersion' : ActorMethod<[bigint], SiteSettings>,
  'runLifecycleCleanup' : ActorMethod<
    [],
    { 'deleted' : bigint, 'archived' : bigint }
  >,
  'saveFbCredentials' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'savePlatformDraft' : ActorMethod<
    [string, SavePlatformDraftArgs],
    { 'ok' : string } |
      { 'err' : AppError }
  >,
  'scrapeListing' : ActorMethod<[string], ScrapeResult>,
  'searchVersionSnapshots' : ActorMethod<
    [[] | [string], [] | [bigint], [] | [bigint]],
    Array<VersionBackupSummary>
  >,
  'setAutoRenewal' : ActorMethod<
    [boolean, bigint],
    { 'ok' : GasWallet } |
      { 'err' : string }
  >,
  'setAutofillPlatformEnabled' : ActorMethod<
    [string, boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setConfig' : ActorMethod<
    [string, string, boolean, string, string],
    undefined
  >,
  'setMaintenanceMode' : ActorMethod<[boolean, string, string], undefined>,
  'setMyUsername' : ActorMethod<[string], SetUsernameResult>,
  'submitSupportTicket' : ActorMethod<
    [string, string, Array<string>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'testAutofill' : ActorMethod<[string], AutofillTestResult>,
  'toggleListingFavorited' : ActorMethod<
    [ListingId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'toggleListingPinned' : ActorMethod<
    [ListingId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'transformGeminiResponse' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'transformGeminiTestResponse' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'transformPaypalTokenResponse' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'transformStripeAccountResponse' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'transformStripeBackupPaymentIntentResponse' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'transformStripeCheckoutResponse' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'transformStripeCustomerResponse' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'transformStripeGasPaymentIntentResponse' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'transformStripePaymentIntentResponse' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'transformStripePortalResponse' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'transformStripeVerifyResponse' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'triggerAdaptiveAutoBackup' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateAdminSettings' : ActorMethod<[UpdateSettingsArgs], SiteSettings>,
  'updateFacebookAutofillSettings' : ActorMethod<
    [boolean, boolean, boolean, boolean, boolean, boolean, boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateListing' : ActorMethod<[UpdateListingArgs], Listing>,
  'updateMasterListing' : ActorMethod<
    [string, UpdateMasterListingArgs],
    { 'ok' : string } |
      { 'err' : AppError }
  >,
  'updateMecariAutofillSettings' : ActorMethod<
    [
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      [] | [bigint],
      boolean,
      [] | [string],
    ],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateMyProfile' : ActorMethod<[UpdateProfileArgs], UpdateProfileResult>,
  'validateAutofillData' : ActorMethod<
    [ExtensionListingData],
    AutofillValidation
  >,
  'validateBackupIntegrity' : ActorMethod<
    [string],
    {
      'valid' : boolean,
      'error' : [] | [string],
      'listingCount' : bigint,
      'userCount' : bigint,
    }
  >,
  'validateCriticalConfig' : ActorMethod<
    [],
    {
      'status' : string,
      'keysConfigured' : boolean,
      'missingKeys' : Array<string>,
    }
  >,
  'validateDiscountCode' : ActorMethod<[string, bigint], [] | [DiscountCode]>,
  'verifyAndGrantPayment' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'verifyEmail' : ActorMethod<[string], VerifyEmailResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];