/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ListingId = IDL.Nat;
export const AddImageArgs = IDL.Record({
  'order' : IDL.Nat,
  'blob' : ExternalBlob,
  'listingId' : ListingId,
  'altText' : IDL.Text,
});
export const ImageId = IDL.Nat;
export const Image = IDL.Record({
  'id' : ImageId,
  'order' : IDL.Nat,
  'blob' : ExternalBlob,
  'listingId' : ListingId,
  'altText' : IDL.Text,
});
export const DiscountType = IDL.Variant({
  'fixedUSD' : IDL.Null,
  'percentage' : IDL.Null,
});
export const DiscountCode = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'discountValue' : IDL.Float64,
  'code' : IDL.Text,
  'discountType' : DiscountType,
  'usageCount' : IDL.Nat,
  'expirationDate' : IDL.Int,
  'tierRestriction' : IDL.Opt(IDL.Nat),
  'maxUses' : IDL.Nat,
});
export const UserId = IDL.Principal;
export const UserTierSubscription = IDL.Record({
  'stripeSubscriptionId' : IDL.Opt(IDL.Text),
  'userId' : IDL.Principal,
  'tier' : IDL.Nat,
  'autoRenewal' : IDL.Bool,
  'updatedAt' : IDL.Int,
  'expirationDate' : IDL.Int,
});
export const PaymentConfig = IDL.Record({
  'stripeProPriceId' : IDL.Opt(IDL.Text),
  'stripeBackupPriceId' : IDL.Opt(IDL.Text),
  'paypalMode' : IDL.Text,
  'stripeSecretKey' : IDL.Opt(IDL.Text),
  'stripeWebhookSecretLive' : IDL.Opt(IDL.Text),
  'stripeWebhookSecretTest' : IDL.Opt(IDL.Text),
  'stripePublishableKey' : IDL.Opt(IDL.Text),
  'stripeMode' : IDL.Text,
  'stripeMaxPriceId' : IDL.Opt(IDL.Text),
  'paypalClientId' : IDL.Opt(IDL.Text),
  'paypalClientSecret' : IDL.Opt(IDL.Text),
  'stripeWebhookSecret' : IDL.Opt(IDL.Text),
  'stripeWalkerPriceId' : IDL.Opt(IDL.Text),
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'stripe' : IDL.Null,
  'crypto' : IDL.Null,
  'paypal' : IDL.Null,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'tierId' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'amountUSD' : IDL.Float64,
  'externalOrderId' : IDL.Opt(IDL.Text),
});
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'fbWebhookToken' : IDL.Opt(IDL.Text),
  'emailVerified' : IDL.Bool,
  'username' : IDL.Text,
  'displayName' : IDL.Opt(IDL.Text),
  'userId' : UserId,
  'createdAt' : Timestamp,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'fbAppId' : IDL.Opt(IDL.Text),
  'fbAccessToken' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'stripeCustomerId' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const AdminTierAction = IDL.Record({
  'tierId' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'newExpirationDate' : IDL.Int,
  'daysAdded' : IDL.Nat,
  'adminId' : IDL.Principal,
});
export const TierConfig = IDL.Record({
  'durationDays' : IDL.Nat,
  'tierId' : IDL.Nat,
  'name' : IDL.Text,
  'stripeProductId' : IDL.Opt(IDL.Text),
  'priceUSD' : IDL.Float64,
});
export const ListingStatus = IDL.Variant({
  'active' : IDL.Null,
  'archived' : IDL.Null,
});
export const Listing = IDL.Record({
  'id' : ListingId,
  'status' : ListingStatus,
  'tierLevel' : IDL.Nat,
  'title' : IDL.Text,
  'favorited' : IDL.Bool,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'sourceUrl' : IDL.Opt(IDL.Text),
  'pinned' : IDL.Bool,
  'expirationDate' : Timestamp,
  'archivedManually' : IDL.Bool,
  'pinnedAt' : IDL.Opt(Timestamp),
  'restoredAt' : IDL.Opt(Timestamp),
  'category' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Text),
  'archivedAt' : IDL.Opt(Timestamp),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NotificationType = IDL.Variant({
  'refuelSuccess' : IDL.Null,
  'lowFuelWarning' : IDL.Null,
  'subscriptionExpiry' : IDL.Null,
  'listingDeletionWarning' : IDL.Null,
  'subscriptionRenewed' : IDL.Null,
  'subscriptionCancelled' : IDL.Null,
  'adminAnnouncement' : IDL.Null,
  'listingArchived' : IDL.Null,
  'paymentFailed' : IDL.Null,
});
export const InAppNotification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const TierName = IDL.Text;
export const GasWallet = IDL.Record({
  'userId' : UserId,
  'autoRenewal' : IDL.Bool,
  'updatedAt' : Timestamp,
  'autoRenewalTierId' : IDL.Nat,
  'gasBalance' : IDL.Nat,
});
export const BackupHistoryRecord = IDL.Record({
  'id' : IDL.Text,
  'downloadExpiresAt' : Timestamp,
  'userId' : UserId,
  'imageCount' : IDL.Nat,
  'exportedAt' : Timestamp,
  'downloadToken' : IDL.Text,
  'listingCount' : IDL.Nat,
  'paymentIntentId' : IDL.Text,
});
export const VersionBackup = IDL.Record({
  'id' : IDL.Text,
  'versionLabel' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Text,
  'isStable' : IDL.Bool,
  'backupData' : IDL.Text,
  'backupType' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
});
export const BackupStatus = IDL.Variant({
  'pending' : IDL.Null,
  'complete' : IDL.Null,
  'failed' : IDL.Null,
});
export const BackupRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : BackupStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'downloadUrl' : IDL.Text,
  'fileSize' : IDL.Nat,
});
export const CreateListingArgs = IDL.Record({
  'tierLevel' : IDL.Opt(IDL.Nat),
  'title' : IDL.Text,
  'description' : IDL.Text,
  'sourceUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Text),
});
export const CreateVersionArgs = IDL.Record({
  'versionLabel' : IDL.Text,
  'description' : IDL.Text,
});
export const SiteSettings = IDL.Record({
  'maxSessionDurationMinutes' : IDL.Nat,
  'appName' : IDL.Text,
  'primaryColor' : IDL.Text,
  'contentModerationEnabled' : IDL.Bool,
  'createdAt' : Timestamp,
  'accentColor' : IDL.Text,
  'updatedAt' : Timestamp,
  'copyButtonsEnabled' : IDL.Bool,
  'maxRequestsPerMinute' : IDL.Nat,
  'maxConcurrentSessions' : IDL.Nat,
  'allowedOrigins' : IDL.Text,
  'uploadEnabled' : IDL.Bool,
  'maxUploadsPerHour' : IDL.Nat,
});
export const AppVersion = IDL.Record({
  'id' : IDL.Nat,
  'versionLabel' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Text,
  'settingsSnapshot' : SiteSettings,
  'isRollback' : IDL.Bool,
});
export const MarketplaceSource = IDL.Variant({
  'facebookMarketplace' : IDL.Null,
  'offerUp' : IDL.Null,
  'unknown' : IDL.Null,
});
export const ListingSnapshot = IDL.Record({
  'title' : IDL.Text,
  'favorited' : IDL.Bool,
  'description' : IDL.Text,
  'pinned' : IDL.Bool,
  'category' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Text),
});
export const BackupImageEntry = IDL.Record({
  'originalUrl' : IDL.Text,
  'filename' : IDL.Text,
});
export const BackupListingEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'favorited' : IDL.Bool,
  'subcategory' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'sourceUrl' : IDL.Opt(IDL.Text),
  'pinned' : IDL.Bool,
  'category' : IDL.Opt(IDL.Text),
  'brand' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Text),
  'typeModel' : IDL.Opt(IDL.Text),
  'condition' : IDL.Opt(IDL.Text),
  'images' : IDL.Vec(BackupImageEntry),
  'archivedAt' : IDL.Opt(Timestamp),
});
export const ConfigEntry = IDL.Record({
  'key' : IDL.Text,
  'value' : IDL.Text,
  'encrypted' : IDL.Bool,
  'updatedAt' : Timestamp,
  'updatedBy' : IDL.Text,
  'category' : IDL.Text,
});
export const AuditLogEntry = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
  'adminId' : UserId,
  'targetUserId' : IDL.Opt(UserId),
});
export const BulkGasDiscount = IDL.Record({
  'minGasAmount' : IDL.Nat,
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
});
export const UserCleanupSummary = IDL.Record({
  'hasExpiredListings' : IDL.Bool,
  'userId' : IDL.Principal,
  'email' : IDL.Text,
  'archivedListingCount' : IDL.Nat,
  'oldestActiveExpirationDate' : IDL.Opt(Timestamp),
  'activeListingCount' : IDL.Nat,
});
export const FbListing = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Text),
});
export const GasPackage = IDL.Record({
  'gasAmount' : IDL.Nat,
  'name' : IDL.Text,
  'stripeProductId' : IDL.Text,
  'priceUSD' : IDL.Float64,
  'packageId' : IDL.Nat,
});
export const HealthStatus = IDL.Record({
  'status' : IDL.Text,
  'backupCount' : IDL.Nat,
  'keysConfigured' : IDL.Bool,
  'lastBackupAt' : Timestamp,
  'criticalKeysPresent' : IDL.Bool,
});
export const LoyaltyStatus = IDL.Record({
  'rewardClaimedForTiers' : IDL.Vec(TierName),
  'currentTier' : TierName,
  'refuelCount' : IDL.Nat,
});
export const FbCredentials = IDL.Record({
  'appId' : IDL.Text,
  'accessToken' : IDL.Text,
});
export const GasPurchaseStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const GasPurchase = IDL.Record({
  'id' : IDL.Nat,
  'status' : GasPurchaseStatus,
  'userId' : UserId,
  'gasAmount' : IDL.Nat,
  'createdAt' : Timestamp,
  'stripePaymentIntentId' : IDL.Text,
  'priceUSD' : IDL.Float64,
});
export const GetProfileResult = IDL.Variant({
  'ok' : UserProfile,
  'err' : IDL.Text,
});
export const OcrFailureEntry = IDL.Record({
  'imageHash' : IDL.Text,
  'errorType' : IDL.Text,
  'userPrincipal' : IDL.Text,
  'timestamp' : IDL.Int,
  'errorReason' : IDL.Text,
});
export const PaymentBannerState = IDL.Record({
  'expiresAt' : IDL.Opt(IDL.Int),
  'bannerType' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'message' : IDL.Text,
});
export const RefuelEntry = IDL.Record({
  'tierAtRefuel' : TierName,
  'date' : IDL.Int,
});
export const SiteAnalytics = IDL.Record({
  'totalListings' : IDL.Nat,
  'avgImagesPerListing' : IDL.Float64,
  'totalArchivedListings' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalImages' : IDL.Nat,
  'paymentRevenue' : IDL.Float64,
  'totalActiveListings' : IDL.Nat,
  'avgListingsPerUser' : IDL.Float64,
});
export const SupportTicket = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'adminReply' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'subject' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'repliedAt' : IDL.Opt(Timestamp),
  'message' : IDL.Text,
});
export const VerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
});
export const VerificationRecord = IDL.Record({
  'status' : VerificationStatus,
  'token' : IDL.Text,
  'expiresAt' : Timestamp,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'resendCount' : IDL.Nat,
  'email' : IDL.Text,
  'lastResendAt' : IDL.Opt(Timestamp),
});
export const VersionBackupSummary = IDL.Record({
  'id' : IDL.Text,
  'versionLabel' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Text,
  'isStable' : IDL.Bool,
  'backupType' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'configCount' : IDL.Nat,
  'sizeKb' : IDL.Nat,
  'listingCount' : IDL.Nat,
  'userCount' : IDL.Nat,
});
export const AdminNotification = IDL.Record({
  'id' : IDL.Nat,
  'notifType' : IDL.Text,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'priority' : IDL.Text,
  'relatedId' : IDL.Opt(IDL.Text),
  'relatedUser' : IDL.Text,
  'targetAdminId' : IDL.Opt(IDL.Text),
});
export const UserSummary = IDL.Record({
  'lastLoginDate' : IDL.Opt(Timestamp),
  'userId' : IDL.Text,
  'role' : IDL.Text,
  'imageCount' : IDL.Nat,
  'registrationDate' : Timestamp,
  'listingCount' : IDL.Nat,
});
export const MarkReadResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
});
export const OcrResult = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'price' : IDL.Text,
  'condition' : IDL.Text,
});
export const ParsedListingResult = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Text),
});
export const ExtensionListingData = IDL.Record({
  'title' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'sourceUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Text),
});
export const DraftListingId = IDL.Nat;
export const SetUsernameResult = IDL.Variant({
  'ok' : UserProfile,
  'err' : IDL.Text,
});
export const ResendResult = IDL.Variant({
  'ok' : IDL.Record({
    'resendCount' : IDL.Nat,
    'cooldownSecondsRemaining' : IDL.Nat,
  }),
  'err' : IDL.Text,
});
export const RestoreResult = IDL.Record({
  'errorMessage' : IDL.Opt(IDL.Text),
  'preSaveBackupId' : IDL.Text,
  'usersRestored' : IDL.Nat,
  'listingsRestored' : IDL.Nat,
  'success' : IDL.Bool,
});
export const ZipRestoreResult = IDL.Record({
  'errorMessage' : IDL.Opt(IDL.Text),
  'listingsRestored' : IDL.Nat,
  'success' : IDL.Bool,
});
export const ScrapedListing = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'imageUrls' : IDL.Vec(IDL.Text),
  'source' : MarketplaceSource,
  'description' : IDL.Opt(IDL.Text),
  'sourceUrl' : IDL.Text,
  'category' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Text),
});
export const ScrapeResult = IDL.Variant({
  'ok' : ScrapedListing,
  'err' : IDL.Text,
});
export const UpdateSettingsArgs = IDL.Record({
  'maxSessionDurationMinutes' : IDL.Nat,
  'appName' : IDL.Text,
  'primaryColor' : IDL.Text,
  'contentModerationEnabled' : IDL.Bool,
  'accentColor' : IDL.Text,
  'copyButtonsEnabled' : IDL.Bool,
  'maxRequestsPerMinute' : IDL.Nat,
  'maxConcurrentSessions' : IDL.Nat,
  'allowedOrigins' : IDL.Text,
  'uploadEnabled' : IDL.Bool,
  'maxUploadsPerHour' : IDL.Nat,
});
export const UpdateListingArgs = IDL.Record({
  'id' : ListingId,
  'tierLevel' : IDL.Opt(IDL.Nat),
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Text),
});
export const UpdateProfileArgs = IDL.Record({
  'displayName' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const UpdateProfileResult = IDL.Variant({
  'ok' : UserProfile,
  'err' : IDL.Text,
});
export const VerifyEmailResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addImage' : IDL.Func([AddImageArgs], [Image], []),
  'adminCreateBackupNow' : IDL.Func(
      [],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'backupId' : IDL.Text, 'createdAt' : IDL.Int }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'adminCreateDiscountCode' : IDL.Func(
      [IDL.Text, DiscountType, IDL.Float64, IDL.Int, IDL.Nat, IDL.Opt(IDL.Nat)],
      [DiscountCode],
      [],
    ),
  'adminDeactivateDiscountCode' : IDL.Func([IDL.Nat], [], []),
  'adminDeleteUser' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminExtendUserTier' : IDL.Func(
      [UserId, IDL.Nat, IDL.Nat],
      [UserTierSubscription],
      [],
    ),
  'adminExtendUserTierByUsername' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : UserTierSubscription, 'err' : IDL.Text })],
      [],
    ),
  'adminGetGeminiConfig' : IDL.Func(
      [],
      [IDL.Record({ 'model' : IDL.Text, 'configured' : IDL.Bool })],
      ['query'],
    ),
  'adminGetPaymentConfig' : IDL.Func([], [PaymentConfig], ['query']),
  'adminGetUserIdByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminGetUserSubscription' : IDL.Func(
      [UserId],
      [IDL.Opt(UserTierSubscription)],
      ['query'],
    ),
  'adminListDiscountCodes' : IDL.Func([], [IDL.Vec(DiscountCode)], ['query']),
  'adminListPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'adminListProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'adminListSubscriptions' : IDL.Func(
      [],
      [IDL.Vec(UserTierSubscription)],
      ['query'],
    ),
  'adminListTierActions' : IDL.Func([], [IDL.Vec(AdminTierAction)], ['query']),
  'adminResetAllUserSubscriptions' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminResetUserSubscription' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminSaveGeminiConfig' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSavePaymentConfig' : IDL.Func(
      [PaymentConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSendAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetGeminiKey' : IDL.Func([IDL.Text], [], []),
  'adminSetMaintenanceMode' : IDL.Func([IDL.Bool, IDL.Text], [], []),
  'adminSetSiteBaseUrl' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetStripeKeys' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'adminSetStripePrices' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'adminTestGeminiConnection' : IDL.Func(
      [],
      [IDL.Record({ 'message' : IDL.Text, 'success' : IDL.Bool })],
      [],
    ),
  'adminTestPaypalConnection' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminTestStripeConnection' : IDL.Func(
      [],
      [IDL.Record({ 'message' : IDL.Text, 'success' : IDL.Bool })],
      [],
    ),
  'adminUpsertTier' : IDL.Func([TierConfig], [], []),
  'archiveListing' : IDL.Func([ListingId], [Listing], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'checkAndCreateLowFuelNotification' : IDL.Func(
      [IDL.Float64, Timestamp],
      [IDL.Opt(InAppNotification)],
      [],
    ),
  'claimLoyaltyReward' : IDL.Func(
      [TierName],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'clearPendingSession' : IDL.Func([], [], []),
  'closeSupportTicket' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'confirmCryptoPayment' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'confirmGasPurchase' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : GasWallet, 'err' : IDL.Text })],
      [],
    ),
  'confirmPayPalPayment' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'confirmSmartBackupPayment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : BackupHistoryRecord, 'err' : IDL.Text })],
      [],
    ),
  'confirmStripePayment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createAdaptiveVersionSnapshot' : IDL.Func([], [IDL.Opt(VersionBackup)], []),
  'createBackupRecord' : IDL.Func([IDL.Nat], [BackupRecord], []),
  'createBroadcastNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'createListing' : IDL.Func([CreateListingArgs], [Listing], []),
  'createStripeCheckoutSession' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createStripePortalSession' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createVersion' : IDL.Func([CreateVersionArgs], [AppVersion], []),
  'createVersionBackup' : IDL.Func(
      [IDL.Bool, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : VersionBackup, 'err' : IDL.Text })],
      [],
    ),
  'debugCheckStripeKeyLength' : IDL.Func([], [IDL.Nat], ['query']),
  'deleteBackup' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteBackupRecord' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteConfig' : IDL.Func([IDL.Text], [], []),
  'deleteListing' : IDL.Func([ListingId], [], []),
  'detectMarketplaceSource' : IDL.Func(
      [IDL.Text],
      [MarketplaceSource],
      ['query'],
    ),
  'dismissPaymentBanner' : IDL.Func([], [], []),
  'exportAllUsersData' : IDL.Func(
      [],
      [IDL.Record({ 'imageUrls' : IDL.Vec(IDL.Text), 'jsonData' : IDL.Text })],
      ['query'],
    ),
  'exportUserData' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({ 'imageUrls' : IDL.Vec(IDL.Text), 'jsonData' : IDL.Text })
        ),
      ],
      ['query'],
    ),
  'exportVersionBackupAsJson' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'failGasPurchase' : IDL.Func([IDL.Nat], [], []),
  'failStripePayment' : IDL.Func([IDL.Nat], [], []),
  'generateBackupData' : IDL.Func([], [IDL.Vec(ListingSnapshot)], ['query']),
  'generateFullBackupEntries' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(IDL.Text)))],
      [IDL.Vec(BackupListingEntry)],
      [],
    ),
  'generateWebhookToken' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getAdaptiveBackupSchedule' : IDL.Func(
      [],
      [
        IDL.Record({
          'intervalHours' : IDL.Nat,
          'nextBackupAt' : IDL.Int,
          'userCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAdminSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getAllConfig' : IDL.Func([], [IDL.Vec(ConfigEntry)], ['query']),
  'getAuditLog' : IDL.Func([], [IDL.Vec(AuditLogEntry)], ['query']),
  'getBackupDownloadInfo' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BackupHistoryRecord)],
      ['query'],
    ),
  'getBackupHistory' : IDL.Func([], [IDL.Vec(BackupHistoryRecord)], ['query']),
  'getBulkGasDiscounts' : IDL.Func([], [IDL.Vec(BulkGasDiscount)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterCyclesBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCleanupSummaries' : IDL.Func(
      [],
      [IDL.Vec(UserCleanupSummary)],
      ['query'],
    ),
  'getConfig' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getFbListings' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(FbListing), 'err' : IDL.Text })],
      [],
    ),
  'getGasPackages' : IDL.Func([], [IDL.Vec(GasPackage)], ['query']),
  'getHealthStatus' : IDL.Func([], [HealthStatus], ['query']),
  'getListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
  'getLoyaltyStatus' : IDL.Func([], [LoyaltyStatus], ['query']),
  'getMaintenanceMode' : IDL.Func(
      [],
      [
        IDL.Record({
          'eta' : IDL.Text,
          'isActive' : IDL.Bool,
          'message' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getMyBackups' : IDL.Func([], [IDL.Vec(BackupRecord)], ['query']),
  'getMyFbCredentials' : IDL.Func([], [IDL.Opt(FbCredentials)], ['query']),
  'getMyGasPurchases' : IDL.Func([], [IDL.Vec(GasPurchase)], ['query']),
  'getMyGasWallet' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : GasWallet, 'err' : IDL.Text })],
      [],
    ),
  'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getMyProfile' : IDL.Func([], [GetProfileResult], ['query']),
  'getMySubscription' : IDL.Func(
      [],
      [IDL.Opt(UserTierSubscription)],
      ['query'],
    ),
  'getMyWebhookToken' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      ['query'],
    ),
  'getOcrFailureLog' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(OcrFailureEntry)],
      ['query'],
    ),
  'getPaymentBanner' : IDL.Func([], [IDL.Opt(PaymentBannerState)], []),
  'getPendingSession' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'tierId' : IDL.Nat,
            'tierDays' : IDL.Nat,
            'sessionId' : IDL.Text,
          })
        ),
      ],
      [],
    ),
  'getProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getPublicConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'maintenanceMessage' : IDL.Text,
          'mode' : IDL.Text,
          'gasWalkerPriceId' : IDL.Text,
          'maintenanceMode' : IDL.Bool,
          'gasLordPriceId' : IDL.Text,
          'gasTravelerPriceId' : IDL.Text,
          'publishableKey' : IDL.Text,
          'siteBaseUrl' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getRefuelHistory' : IDL.Func([], [IDL.Vec(RefuelEntry)], ['query']),
  'getRevenueStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'month' : IDL.Nat,
          'today' : IDL.Nat,
          'week' : IDL.Nat,
          'activeSubscribers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getSiteAnalytics' : IDL.Func([], [SiteAnalytics], ['query']),
  'getSiteBaseUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getStripeHealthStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'status' : IDL.Text,
          'lastWebhookReceived' : IDL.Opt(IDL.Int),
          'keysConfigured' : IDL.Bool,
          'webhookConfigured' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getStripePublicKey' : IDL.Func(
      [],
      [IDL.Record({ 'publishableKey' : IDL.Text })],
      ['query'],
    ),
  'getSupportTicket' : IDL.Func([IDL.Nat], [IDL.Opt(SupportTicket)], ['query']),
  'getSystemHealthStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'stripe' : IDL.Record({
            'status' : IDL.Text,
            'hasPublishableKey' : IDL.Bool,
            'lastWebhookAt' : IDL.Opt(IDL.Int),
            'hasPriceIds' : IDL.Bool,
            'hasSecretKey' : IDL.Bool,
          }),
          'signups' : IDL.Record({
            'total' : IDL.Nat,
            'lastSignupAt' : IDL.Opt(IDL.Int),
          }),
          'backup' : IDL.Record({
            'status' : IDL.Text,
            'freshnessHours' : IDL.Opt(IDL.Nat),
            'backupCount' : IDL.Nat,
            'lastBackupAt' : IDL.Opt(IDL.Int),
          }),
          'database' : IDL.Record({
            'status' : IDL.Text,
            'canReadConfig' : IDL.Bool,
            'canReadUsers' : IDL.Bool,
          }),
          'gemini' : IDL.Record({
            'status' : IDL.Text,
            'hasApiKey' : IDL.Bool,
          }),
          'maintenance' : IDL.Record({ 'isActive' : IDL.Bool }),
          'paypal' : IDL.Record({
            'status' : IDL.Text,
            'isConfigured' : IDL.Bool,
          }),
        }),
      ],
      ['query'],
    ),
  'getTier' : IDL.Func([IDL.Nat], [IDL.Opt(TierConfig)], ['query']),
  'getTiers' : IDL.Func([], [IDL.Vec(TierConfig)], ['query']),
  'getUnreadAdminNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserNotifications' : IDL.Func(
      [],
      [IDL.Vec(InAppNotification)],
      ['query'],
    ),
  'getVerificationStatus' : IDL.Func(
      [],
      [IDL.Opt(VerificationRecord)],
      ['query'],
    ),
  'getVersionSnapshotList' : IDL.Func(
      [],
      [IDL.Vec(VersionBackupSummary)],
      ['query'],
    ),
  'initConfigFromPaymentConfig' : IDL.Func([], [], []),
  'initiateCryptoPayment' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : PaymentRecord, 'err' : IDL.Text })],
      [],
    ),
  'initiateEmailVerification' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'initiateGasPurchase' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text)],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'gasAmount' : IDL.Nat,
            'purchaseRecordId' : IDL.Nat,
            'finalAmountUSD' : IDL.Float64,
            'stripeClientSecret' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'initiatePayPalPayment' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : PaymentRecord, 'err' : IDL.Text })],
      [],
    ),
  'initiateSmartBackup' : IDL.Func(
      [],
      [
        IDL.Record({
          'paymentRecordId' : IDL.Nat,
          'backupPriceId' : IDL.Opt(IDL.Text),
          'amountUSD' : IDL.Float64,
          'stripeClientSecret' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
    ),
  'initiateTierUpgrade' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text)],
      [
        IDL.Record({
          'tierDurationDays' : IDL.Nat,
          'discountApplied' : IDL.Bool,
          'paymentRecordId' : IDL.Nat,
          'finalAmountUSD' : IDL.Float64,
          'stripeClientSecret' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAdminNotifications' : IDL.Func(
      [],
      [IDL.Vec(AdminNotification)],
      ['query'],
    ),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
  'listFavoritedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'listImages' : IDL.Func([ListingId], [IDL.Vec(Image)], ['query']),
  'listListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'listSupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'listVersionBackups' : IDL.Func(
      [],
      [IDL.Vec(VersionBackupSummary)],
      ['query'],
    ),
  'listVersionHistory' : IDL.Func([], [IDL.Vec(AppVersion)], ['query']),
  'markAdminNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'markAllAdminNotificationsRead' : IDL.Func([], [], []),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markBackupAsStable' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [MarkReadResult], []),
  'ocrScanImage' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : OcrResult, 'err' : IDL.Text })],
      [],
    ),
  'parsePastedText' : IDL.Func([IDL.Text], [ParsedListingResult], []),
  'permanentDeleteListing' : IDL.Func(
      [ListingId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'receiveExtensionData' : IDL.Func(
      [ExtensionListingData, IDL.Text],
      [IDL.Variant({ 'ok' : DraftListingId, 'err' : IDL.Text })],
      [],
    ),
  'registerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text],
      [SetUsernameResult],
      [],
    ),
  'removeImage' : IDL.Func([ImageId], [], []),
  'replySupportTicket' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resendVerificationEmail' : IDL.Func([IDL.Text], [ResendResult], []),
  'restoreFromBackup' : IDL.Func(
      [IDL.Vec(ListingSnapshot)],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'restoreFromJsonBlob' : IDL.Func([IDL.Text], [RestoreResult], []),
  'restoreFromVersionBackup' : IDL.Func([IDL.Text], [RestoreResult], []),
  'restoreFromZipBackup' : IDL.Func(
      [IDL.Vec(BackupListingEntry)],
      [ZipRestoreResult],
      [],
    ),
  'restoreListing' : IDL.Func(
      [ListingId],
      [IDL.Variant({ 'ok' : Listing, 'err' : IDL.Text })],
      [],
    ),
  'restoreUserAccountFromBackup' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'rollbackToVersion' : IDL.Func([IDL.Nat], [SiteSettings], []),
  'runLifecycleCleanup' : IDL.Func(
      [],
      [IDL.Record({ 'deleted' : IDL.Nat, 'archived' : IDL.Nat })],
      [],
    ),
  'saveFbCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'scrapeListing' : IDL.Func([IDL.Text], [ScrapeResult], []),
  'setAutoRenewal' : IDL.Func(
      [IDL.Bool, IDL.Nat],
      [IDL.Variant({ 'ok' : GasWallet, 'err' : IDL.Text })],
      [],
    ),
  'setConfig' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'setMaintenanceMode' : IDL.Func([IDL.Bool, IDL.Text, IDL.Text], [], []),
  'setMyUsername' : IDL.Func([IDL.Text], [SetUsernameResult], []),
  'submitSupportTicket' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'toggleListingFavorited' : IDL.Func(
      [ListingId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'toggleListingPinned' : IDL.Func(
      [ListingId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'transformGeminiResponse' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'transformGeminiTestResponse' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'transformPaypalTokenResponse' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'transformStripeAccountResponse' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'transformStripeBackupPaymentIntentResponse' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'transformStripeCheckoutResponse' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'transformStripeCustomerResponse' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'transformStripeGasPaymentIntentResponse' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'transformStripePaymentIntentResponse' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'transformStripePortalResponse' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'transformStripeVerifyResponse' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'triggerAdaptiveAutoBackup' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateAdminSettings' : IDL.Func([UpdateSettingsArgs], [SiteSettings], []),
  'updateListing' : IDL.Func([UpdateListingArgs], [Listing], []),
  'updateMyProfile' : IDL.Func([UpdateProfileArgs], [UpdateProfileResult], []),
  'validateDiscountCode' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(DiscountCode)],
      ['query'],
    ),
  'verifyAndGrantPayment' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'verifyEmail' : IDL.Func([IDL.Text], [VerifyEmailResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ListingId = IDL.Nat;
  const AddImageArgs = IDL.Record({
    'order' : IDL.Nat,
    'blob' : ExternalBlob,
    'listingId' : ListingId,
    'altText' : IDL.Text,
  });
  const ImageId = IDL.Nat;
  const Image = IDL.Record({
    'id' : ImageId,
    'order' : IDL.Nat,
    'blob' : ExternalBlob,
    'listingId' : ListingId,
    'altText' : IDL.Text,
  });
  const DiscountType = IDL.Variant({
    'fixedUSD' : IDL.Null,
    'percentage' : IDL.Null,
  });
  const DiscountCode = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'discountValue' : IDL.Float64,
    'code' : IDL.Text,
    'discountType' : DiscountType,
    'usageCount' : IDL.Nat,
    'expirationDate' : IDL.Int,
    'tierRestriction' : IDL.Opt(IDL.Nat),
    'maxUses' : IDL.Nat,
  });
  const UserId = IDL.Principal;
  const UserTierSubscription = IDL.Record({
    'stripeSubscriptionId' : IDL.Opt(IDL.Text),
    'userId' : IDL.Principal,
    'tier' : IDL.Nat,
    'autoRenewal' : IDL.Bool,
    'updatedAt' : IDL.Int,
    'expirationDate' : IDL.Int,
  });
  const PaymentConfig = IDL.Record({
    'stripeProPriceId' : IDL.Opt(IDL.Text),
    'stripeBackupPriceId' : IDL.Opt(IDL.Text),
    'paypalMode' : IDL.Text,
    'stripeSecretKey' : IDL.Opt(IDL.Text),
    'stripeWebhookSecretLive' : IDL.Opt(IDL.Text),
    'stripeWebhookSecretTest' : IDL.Opt(IDL.Text),
    'stripePublishableKey' : IDL.Opt(IDL.Text),
    'stripeMode' : IDL.Text,
    'stripeMaxPriceId' : IDL.Opt(IDL.Text),
    'paypalClientId' : IDL.Opt(IDL.Text),
    'paypalClientSecret' : IDL.Opt(IDL.Text),
    'stripeWebhookSecret' : IDL.Opt(IDL.Text),
    'stripeWalkerPriceId' : IDL.Opt(IDL.Text),
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'stripe' : IDL.Null,
    'crypto' : IDL.Null,
    'paypal' : IDL.Null,
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'tierId' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'amountUSD' : IDL.Float64,
    'externalOrderId' : IDL.Opt(IDL.Text),
  });
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'fbWebhookToken' : IDL.Opt(IDL.Text),
    'emailVerified' : IDL.Bool,
    'username' : IDL.Text,
    'displayName' : IDL.Opt(IDL.Text),
    'userId' : UserId,
    'createdAt' : Timestamp,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'fbAppId' : IDL.Opt(IDL.Text),
    'fbAccessToken' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'stripeCustomerId' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const AdminTierAction = IDL.Record({
    'tierId' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'newExpirationDate' : IDL.Int,
    'daysAdded' : IDL.Nat,
    'adminId' : IDL.Principal,
  });
  const TierConfig = IDL.Record({
    'durationDays' : IDL.Nat,
    'tierId' : IDL.Nat,
    'name' : IDL.Text,
    'stripeProductId' : IDL.Opt(IDL.Text),
    'priceUSD' : IDL.Float64,
  });
  const ListingStatus = IDL.Variant({
    'active' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Listing = IDL.Record({
    'id' : ListingId,
    'status' : ListingStatus,
    'tierLevel' : IDL.Nat,
    'title' : IDL.Text,
    'favorited' : IDL.Bool,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'sourceUrl' : IDL.Opt(IDL.Text),
    'pinned' : IDL.Bool,
    'expirationDate' : Timestamp,
    'archivedManually' : IDL.Bool,
    'pinnedAt' : IDL.Opt(Timestamp),
    'restoredAt' : IDL.Opt(Timestamp),
    'category' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Text),
    'archivedAt' : IDL.Opt(Timestamp),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NotificationType = IDL.Variant({
    'refuelSuccess' : IDL.Null,
    'lowFuelWarning' : IDL.Null,
    'subscriptionExpiry' : IDL.Null,
    'listingDeletionWarning' : IDL.Null,
    'subscriptionRenewed' : IDL.Null,
    'subscriptionCancelled' : IDL.Null,
    'adminAnnouncement' : IDL.Null,
    'listingArchived' : IDL.Null,
    'paymentFailed' : IDL.Null,
  });
  const InAppNotification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'userId' : UserId,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const TierName = IDL.Text;
  const GasWallet = IDL.Record({
    'userId' : UserId,
    'autoRenewal' : IDL.Bool,
    'updatedAt' : Timestamp,
    'autoRenewalTierId' : IDL.Nat,
    'gasBalance' : IDL.Nat,
  });
  const BackupHistoryRecord = IDL.Record({
    'id' : IDL.Text,
    'downloadExpiresAt' : Timestamp,
    'userId' : UserId,
    'imageCount' : IDL.Nat,
    'exportedAt' : Timestamp,
    'downloadToken' : IDL.Text,
    'listingCount' : IDL.Nat,
    'paymentIntentId' : IDL.Text,
  });
  const VersionBackup = IDL.Record({
    'id' : IDL.Text,
    'versionLabel' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Text,
    'isStable' : IDL.Bool,
    'backupData' : IDL.Text,
    'backupType' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
  });
  const BackupStatus = IDL.Variant({
    'pending' : IDL.Null,
    'complete' : IDL.Null,
    'failed' : IDL.Null,
  });
  const BackupRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : BackupStatus,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'downloadUrl' : IDL.Text,
    'fileSize' : IDL.Nat,
  });
  const CreateListingArgs = IDL.Record({
    'tierLevel' : IDL.Opt(IDL.Nat),
    'title' : IDL.Text,
    'description' : IDL.Text,
    'sourceUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Text),
  });
  const CreateVersionArgs = IDL.Record({
    'versionLabel' : IDL.Text,
    'description' : IDL.Text,
  });
  const SiteSettings = IDL.Record({
    'maxSessionDurationMinutes' : IDL.Nat,
    'appName' : IDL.Text,
    'primaryColor' : IDL.Text,
    'contentModerationEnabled' : IDL.Bool,
    'createdAt' : Timestamp,
    'accentColor' : IDL.Text,
    'updatedAt' : Timestamp,
    'copyButtonsEnabled' : IDL.Bool,
    'maxRequestsPerMinute' : IDL.Nat,
    'maxConcurrentSessions' : IDL.Nat,
    'allowedOrigins' : IDL.Text,
    'uploadEnabled' : IDL.Bool,
    'maxUploadsPerHour' : IDL.Nat,
  });
  const AppVersion = IDL.Record({
    'id' : IDL.Nat,
    'versionLabel' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Text,
    'settingsSnapshot' : SiteSettings,
    'isRollback' : IDL.Bool,
  });
  const MarketplaceSource = IDL.Variant({
    'facebookMarketplace' : IDL.Null,
    'offerUp' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const ListingSnapshot = IDL.Record({
    'title' : IDL.Text,
    'favorited' : IDL.Bool,
    'description' : IDL.Text,
    'pinned' : IDL.Bool,
    'category' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Text),
  });
  const BackupImageEntry = IDL.Record({
    'originalUrl' : IDL.Text,
    'filename' : IDL.Text,
  });
  const BackupListingEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'favorited' : IDL.Bool,
    'subcategory' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'sourceUrl' : IDL.Opt(IDL.Text),
    'pinned' : IDL.Bool,
    'category' : IDL.Opt(IDL.Text),
    'brand' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Text),
    'typeModel' : IDL.Opt(IDL.Text),
    'condition' : IDL.Opt(IDL.Text),
    'images' : IDL.Vec(BackupImageEntry),
    'archivedAt' : IDL.Opt(Timestamp),
  });
  const ConfigEntry = IDL.Record({
    'key' : IDL.Text,
    'value' : IDL.Text,
    'encrypted' : IDL.Bool,
    'updatedAt' : Timestamp,
    'updatedBy' : IDL.Text,
    'category' : IDL.Text,
  });
  const AuditLogEntry = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
    'adminId' : UserId,
    'targetUserId' : IDL.Opt(UserId),
  });
  const BulkGasDiscount = IDL.Record({
    'minGasAmount' : IDL.Nat,
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
  });
  const UserCleanupSummary = IDL.Record({
    'hasExpiredListings' : IDL.Bool,
    'userId' : IDL.Principal,
    'email' : IDL.Text,
    'archivedListingCount' : IDL.Nat,
    'oldestActiveExpirationDate' : IDL.Opt(Timestamp),
    'activeListingCount' : IDL.Nat,
  });
  const FbListing = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Text),
  });
  const GasPackage = IDL.Record({
    'gasAmount' : IDL.Nat,
    'name' : IDL.Text,
    'stripeProductId' : IDL.Text,
    'priceUSD' : IDL.Float64,
    'packageId' : IDL.Nat,
  });
  const HealthStatus = IDL.Record({
    'status' : IDL.Text,
    'backupCount' : IDL.Nat,
    'keysConfigured' : IDL.Bool,
    'lastBackupAt' : Timestamp,
    'criticalKeysPresent' : IDL.Bool,
  });
  const LoyaltyStatus = IDL.Record({
    'rewardClaimedForTiers' : IDL.Vec(TierName),
    'currentTier' : TierName,
    'refuelCount' : IDL.Nat,
  });
  const FbCredentials = IDL.Record({
    'appId' : IDL.Text,
    'accessToken' : IDL.Text,
  });
  const GasPurchaseStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const GasPurchase = IDL.Record({
    'id' : IDL.Nat,
    'status' : GasPurchaseStatus,
    'userId' : UserId,
    'gasAmount' : IDL.Nat,
    'createdAt' : Timestamp,
    'stripePaymentIntentId' : IDL.Text,
    'priceUSD' : IDL.Float64,
  });
  const GetProfileResult = IDL.Variant({
    'ok' : UserProfile,
    'err' : IDL.Text,
  });
  const OcrFailureEntry = IDL.Record({
    'imageHash' : IDL.Text,
    'errorType' : IDL.Text,
    'userPrincipal' : IDL.Text,
    'timestamp' : IDL.Int,
    'errorReason' : IDL.Text,
  });
  const PaymentBannerState = IDL.Record({
    'expiresAt' : IDL.Opt(IDL.Int),
    'bannerType' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'message' : IDL.Text,
  });
  const RefuelEntry = IDL.Record({
    'tierAtRefuel' : TierName,
    'date' : IDL.Int,
  });
  const SiteAnalytics = IDL.Record({
    'totalListings' : IDL.Nat,
    'avgImagesPerListing' : IDL.Float64,
    'totalArchivedListings' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalImages' : IDL.Nat,
    'paymentRevenue' : IDL.Float64,
    'totalActiveListings' : IDL.Nat,
    'avgListingsPerUser' : IDL.Float64,
  });
  const SupportTicket = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'adminReply' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'subject' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'repliedAt' : IDL.Opt(Timestamp),
    'message' : IDL.Text,
  });
  const VerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
  });
  const VerificationRecord = IDL.Record({
    'status' : VerificationStatus,
    'token' : IDL.Text,
    'expiresAt' : Timestamp,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'resendCount' : IDL.Nat,
    'email' : IDL.Text,
    'lastResendAt' : IDL.Opt(Timestamp),
  });
  const VersionBackupSummary = IDL.Record({
    'id' : IDL.Text,
    'versionLabel' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Text,
    'isStable' : IDL.Bool,
    'backupType' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'configCount' : IDL.Nat,
    'sizeKb' : IDL.Nat,
    'listingCount' : IDL.Nat,
    'userCount' : IDL.Nat,
  });
  const AdminNotification = IDL.Record({
    'id' : IDL.Nat,
    'notifType' : IDL.Text,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'priority' : IDL.Text,
    'relatedId' : IDL.Opt(IDL.Text),
    'relatedUser' : IDL.Text,
    'targetAdminId' : IDL.Opt(IDL.Text),
  });
  const UserSummary = IDL.Record({
    'lastLoginDate' : IDL.Opt(Timestamp),
    'userId' : IDL.Text,
    'role' : IDL.Text,
    'imageCount' : IDL.Nat,
    'registrationDate' : Timestamp,
    'listingCount' : IDL.Nat,
  });
  const MarkReadResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const OcrResult = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'price' : IDL.Text,
    'condition' : IDL.Text,
  });
  const ParsedListingResult = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Text),
  });
  const ExtensionListingData = IDL.Record({
    'title' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'sourceUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Text),
  });
  const DraftListingId = IDL.Nat;
  const SetUsernameResult = IDL.Variant({
    'ok' : UserProfile,
    'err' : IDL.Text,
  });
  const ResendResult = IDL.Variant({
    'ok' : IDL.Record({
      'resendCount' : IDL.Nat,
      'cooldownSecondsRemaining' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const RestoreResult = IDL.Record({
    'errorMessage' : IDL.Opt(IDL.Text),
    'preSaveBackupId' : IDL.Text,
    'usersRestored' : IDL.Nat,
    'listingsRestored' : IDL.Nat,
    'success' : IDL.Bool,
  });
  const ZipRestoreResult = IDL.Record({
    'errorMessage' : IDL.Opt(IDL.Text),
    'listingsRestored' : IDL.Nat,
    'success' : IDL.Bool,
  });
  const ScrapedListing = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'imageUrls' : IDL.Vec(IDL.Text),
    'source' : MarketplaceSource,
    'description' : IDL.Opt(IDL.Text),
    'sourceUrl' : IDL.Text,
    'category' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Text),
  });
  const ScrapeResult = IDL.Variant({ 'ok' : ScrapedListing, 'err' : IDL.Text });
  const UpdateSettingsArgs = IDL.Record({
    'maxSessionDurationMinutes' : IDL.Nat,
    'appName' : IDL.Text,
    'primaryColor' : IDL.Text,
    'contentModerationEnabled' : IDL.Bool,
    'accentColor' : IDL.Text,
    'copyButtonsEnabled' : IDL.Bool,
    'maxRequestsPerMinute' : IDL.Nat,
    'maxConcurrentSessions' : IDL.Nat,
    'allowedOrigins' : IDL.Text,
    'uploadEnabled' : IDL.Bool,
    'maxUploadsPerHour' : IDL.Nat,
  });
  const UpdateListingArgs = IDL.Record({
    'id' : ListingId,
    'tierLevel' : IDL.Opt(IDL.Nat),
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Text),
  });
  const UpdateProfileArgs = IDL.Record({
    'displayName' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const UpdateProfileResult = IDL.Variant({
    'ok' : UserProfile,
    'err' : IDL.Text,
  });
  const VerifyEmailResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addImage' : IDL.Func([AddImageArgs], [Image], []),
    'adminCreateBackupNow' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'backupId' : IDL.Text, 'createdAt' : IDL.Int }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'adminCreateDiscountCode' : IDL.Func(
        [
          IDL.Text,
          DiscountType,
          IDL.Float64,
          IDL.Int,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
        ],
        [DiscountCode],
        [],
      ),
    'adminDeactivateDiscountCode' : IDL.Func([IDL.Nat], [], []),
    'adminDeleteUser' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminExtendUserTier' : IDL.Func(
        [UserId, IDL.Nat, IDL.Nat],
        [UserTierSubscription],
        [],
      ),
    'adminExtendUserTierByUsername' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : UserTierSubscription, 'err' : IDL.Text })],
        [],
      ),
    'adminGetGeminiConfig' : IDL.Func(
        [],
        [IDL.Record({ 'model' : IDL.Text, 'configured' : IDL.Bool })],
        ['query'],
      ),
    'adminGetPaymentConfig' : IDL.Func([], [PaymentConfig], ['query']),
    'adminGetUserIdByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminGetUserSubscription' : IDL.Func(
        [UserId],
        [IDL.Opt(UserTierSubscription)],
        ['query'],
      ),
    'adminListDiscountCodes' : IDL.Func([], [IDL.Vec(DiscountCode)], ['query']),
    'adminListPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'adminListProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'adminListSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(UserTierSubscription)],
        ['query'],
      ),
    'adminListTierActions' : IDL.Func(
        [],
        [IDL.Vec(AdminTierAction)],
        ['query'],
      ),
    'adminResetAllUserSubscriptions' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminResetUserSubscription' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminSaveGeminiConfig' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSavePaymentConfig' : IDL.Func(
        [PaymentConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSendAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetGeminiKey' : IDL.Func([IDL.Text], [], []),
    'adminSetMaintenanceMode' : IDL.Func([IDL.Bool, IDL.Text], [], []),
    'adminSetSiteBaseUrl' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetStripeKeys' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'adminSetStripePrices' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'adminTestGeminiConnection' : IDL.Func(
        [],
        [IDL.Record({ 'message' : IDL.Text, 'success' : IDL.Bool })],
        [],
      ),
    'adminTestPaypalConnection' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminTestStripeConnection' : IDL.Func(
        [],
        [IDL.Record({ 'message' : IDL.Text, 'success' : IDL.Bool })],
        [],
      ),
    'adminUpsertTier' : IDL.Func([TierConfig], [], []),
    'archiveListing' : IDL.Func([ListingId], [Listing], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'checkAndCreateLowFuelNotification' : IDL.Func(
        [IDL.Float64, Timestamp],
        [IDL.Opt(InAppNotification)],
        [],
      ),
    'claimLoyaltyReward' : IDL.Func(
        [TierName],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'clearPendingSession' : IDL.Func([], [], []),
    'closeSupportTicket' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'confirmCryptoPayment' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'confirmGasPurchase' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : GasWallet, 'err' : IDL.Text })],
        [],
      ),
    'confirmPayPalPayment' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'confirmSmartBackupPayment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : BackupHistoryRecord, 'err' : IDL.Text })],
        [],
      ),
    'confirmStripePayment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createAdaptiveVersionSnapshot' : IDL.Func(
        [],
        [IDL.Opt(VersionBackup)],
        [],
      ),
    'createBackupRecord' : IDL.Func([IDL.Nat], [BackupRecord], []),
    'createBroadcastNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'createListing' : IDL.Func([CreateListingArgs], [Listing], []),
    'createStripeCheckoutSession' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createStripePortalSession' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createVersion' : IDL.Func([CreateVersionArgs], [AppVersion], []),
    'createVersionBackup' : IDL.Func(
        [IDL.Bool, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : VersionBackup, 'err' : IDL.Text })],
        [],
      ),
    'debugCheckStripeKeyLength' : IDL.Func([], [IDL.Nat], ['query']),
    'deleteBackup' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteBackupRecord' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteConfig' : IDL.Func([IDL.Text], [], []),
    'deleteListing' : IDL.Func([ListingId], [], []),
    'detectMarketplaceSource' : IDL.Func(
        [IDL.Text],
        [MarketplaceSource],
        ['query'],
      ),
    'dismissPaymentBanner' : IDL.Func([], [], []),
    'exportAllUsersData' : IDL.Func(
        [],
        [
          IDL.Record({
            'imageUrls' : IDL.Vec(IDL.Text),
            'jsonData' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'exportUserData' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'imageUrls' : IDL.Vec(IDL.Text),
              'jsonData' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'exportVersionBackupAsJson' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'failGasPurchase' : IDL.Func([IDL.Nat], [], []),
    'failStripePayment' : IDL.Func([IDL.Nat], [], []),
    'generateBackupData' : IDL.Func([], [IDL.Vec(ListingSnapshot)], ['query']),
    'generateFullBackupEntries' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(IDL.Text)))],
        [IDL.Vec(BackupListingEntry)],
        [],
      ),
    'generateWebhookToken' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getAdaptiveBackupSchedule' : IDL.Func(
        [],
        [
          IDL.Record({
            'intervalHours' : IDL.Nat,
            'nextBackupAt' : IDL.Int,
            'userCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAdminSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getAllConfig' : IDL.Func([], [IDL.Vec(ConfigEntry)], ['query']),
    'getAuditLog' : IDL.Func([], [IDL.Vec(AuditLogEntry)], ['query']),
    'getBackupDownloadInfo' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BackupHistoryRecord)],
        ['query'],
      ),
    'getBackupHistory' : IDL.Func(
        [],
        [IDL.Vec(BackupHistoryRecord)],
        ['query'],
      ),
    'getBulkGasDiscounts' : IDL.Func([], [IDL.Vec(BulkGasDiscount)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterCyclesBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCleanupSummaries' : IDL.Func(
        [],
        [IDL.Vec(UserCleanupSummary)],
        ['query'],
      ),
    'getConfig' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getFbListings' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(FbListing), 'err' : IDL.Text })],
        [],
      ),
    'getGasPackages' : IDL.Func([], [IDL.Vec(GasPackage)], ['query']),
    'getHealthStatus' : IDL.Func([], [HealthStatus], ['query']),
    'getListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
    'getLoyaltyStatus' : IDL.Func([], [LoyaltyStatus], ['query']),
    'getMaintenanceMode' : IDL.Func(
        [],
        [
          IDL.Record({
            'eta' : IDL.Text,
            'isActive' : IDL.Bool,
            'message' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getMyBackups' : IDL.Func([], [IDL.Vec(BackupRecord)], ['query']),
    'getMyFbCredentials' : IDL.Func([], [IDL.Opt(FbCredentials)], ['query']),
    'getMyGasPurchases' : IDL.Func([], [IDL.Vec(GasPurchase)], ['query']),
    'getMyGasWallet' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : GasWallet, 'err' : IDL.Text })],
        [],
      ),
    'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getMyProfile' : IDL.Func([], [GetProfileResult], ['query']),
    'getMySubscription' : IDL.Func(
        [],
        [IDL.Opt(UserTierSubscription)],
        ['query'],
      ),
    'getMyWebhookToken' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        ['query'],
      ),
    'getOcrFailureLog' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(OcrFailureEntry)],
        ['query'],
      ),
    'getPaymentBanner' : IDL.Func([], [IDL.Opt(PaymentBannerState)], []),
    'getPendingSession' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'tierId' : IDL.Nat,
              'tierDays' : IDL.Nat,
              'sessionId' : IDL.Text,
            })
          ),
        ],
        [],
      ),
    'getProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getPublicConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'maintenanceMessage' : IDL.Text,
            'mode' : IDL.Text,
            'gasWalkerPriceId' : IDL.Text,
            'maintenanceMode' : IDL.Bool,
            'gasLordPriceId' : IDL.Text,
            'gasTravelerPriceId' : IDL.Text,
            'publishableKey' : IDL.Text,
            'siteBaseUrl' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getRefuelHistory' : IDL.Func([], [IDL.Vec(RefuelEntry)], ['query']),
    'getRevenueStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'month' : IDL.Nat,
            'today' : IDL.Nat,
            'week' : IDL.Nat,
            'activeSubscribers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getSiteAnalytics' : IDL.Func([], [SiteAnalytics], ['query']),
    'getSiteBaseUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getStripeHealthStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'status' : IDL.Text,
            'lastWebhookReceived' : IDL.Opt(IDL.Int),
            'keysConfigured' : IDL.Bool,
            'webhookConfigured' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getStripePublicKey' : IDL.Func(
        [],
        [IDL.Record({ 'publishableKey' : IDL.Text })],
        ['query'],
      ),
    'getSupportTicket' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SupportTicket)],
        ['query'],
      ),
    'getSystemHealthStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'stripe' : IDL.Record({
              'status' : IDL.Text,
              'hasPublishableKey' : IDL.Bool,
              'lastWebhookAt' : IDL.Opt(IDL.Int),
              'hasPriceIds' : IDL.Bool,
              'hasSecretKey' : IDL.Bool,
            }),
            'signups' : IDL.Record({
              'total' : IDL.Nat,
              'lastSignupAt' : IDL.Opt(IDL.Int),
            }),
            'backup' : IDL.Record({
              'status' : IDL.Text,
              'freshnessHours' : IDL.Opt(IDL.Nat),
              'backupCount' : IDL.Nat,
              'lastBackupAt' : IDL.Opt(IDL.Int),
            }),
            'database' : IDL.Record({
              'status' : IDL.Text,
              'canReadConfig' : IDL.Bool,
              'canReadUsers' : IDL.Bool,
            }),
            'gemini' : IDL.Record({
              'status' : IDL.Text,
              'hasApiKey' : IDL.Bool,
            }),
            'maintenance' : IDL.Record({ 'isActive' : IDL.Bool }),
            'paypal' : IDL.Record({
              'status' : IDL.Text,
              'isConfigured' : IDL.Bool,
            }),
          }),
        ],
        ['query'],
      ),
    'getTier' : IDL.Func([IDL.Nat], [IDL.Opt(TierConfig)], ['query']),
    'getTiers' : IDL.Func([], [IDL.Vec(TierConfig)], ['query']),
    'getUnreadAdminNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserNotifications' : IDL.Func(
        [],
        [IDL.Vec(InAppNotification)],
        ['query'],
      ),
    'getVerificationStatus' : IDL.Func(
        [],
        [IDL.Opt(VerificationRecord)],
        ['query'],
      ),
    'getVersionSnapshotList' : IDL.Func(
        [],
        [IDL.Vec(VersionBackupSummary)],
        ['query'],
      ),
    'initConfigFromPaymentConfig' : IDL.Func([], [], []),
    'initiateCryptoPayment' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : PaymentRecord, 'err' : IDL.Text })],
        [],
      ),
    'initiateEmailVerification' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'initiateGasPurchase' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text)],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'gasAmount' : IDL.Nat,
              'purchaseRecordId' : IDL.Nat,
              'finalAmountUSD' : IDL.Float64,
              'stripeClientSecret' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'initiatePayPalPayment' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : PaymentRecord, 'err' : IDL.Text })],
        [],
      ),
    'initiateSmartBackup' : IDL.Func(
        [],
        [
          IDL.Record({
            'paymentRecordId' : IDL.Nat,
            'backupPriceId' : IDL.Opt(IDL.Text),
            'amountUSD' : IDL.Float64,
            'stripeClientSecret' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
      ),
    'initiateTierUpgrade' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text)],
        [
          IDL.Record({
            'tierDurationDays' : IDL.Nat,
            'discountApplied' : IDL.Bool,
            'paymentRecordId' : IDL.Nat,
            'finalAmountUSD' : IDL.Float64,
            'stripeClientSecret' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAdminNotifications' : IDL.Func(
        [],
        [IDL.Vec(AdminNotification)],
        ['query'],
      ),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
    'listFavoritedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'listImages' : IDL.Func([ListingId], [IDL.Vec(Image)], ['query']),
    'listListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'listSupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'listVersionBackups' : IDL.Func(
        [],
        [IDL.Vec(VersionBackupSummary)],
        ['query'],
      ),
    'listVersionHistory' : IDL.Func([], [IDL.Vec(AppVersion)], ['query']),
    'markAdminNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'markAllAdminNotificationsRead' : IDL.Func([], [], []),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markBackupAsStable' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [MarkReadResult], []),
    'ocrScanImage' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : OcrResult, 'err' : IDL.Text })],
        [],
      ),
    'parsePastedText' : IDL.Func([IDL.Text], [ParsedListingResult], []),
    'permanentDeleteListing' : IDL.Func(
        [ListingId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'receiveExtensionData' : IDL.Func(
        [ExtensionListingData, IDL.Text],
        [IDL.Variant({ 'ok' : DraftListingId, 'err' : IDL.Text })],
        [],
      ),
    'registerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text],
        [SetUsernameResult],
        [],
      ),
    'removeImage' : IDL.Func([ImageId], [], []),
    'replySupportTicket' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resendVerificationEmail' : IDL.Func([IDL.Text], [ResendResult], []),
    'restoreFromBackup' : IDL.Func(
        [IDL.Vec(ListingSnapshot)],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'restoreFromJsonBlob' : IDL.Func([IDL.Text], [RestoreResult], []),
    'restoreFromVersionBackup' : IDL.Func([IDL.Text], [RestoreResult], []),
    'restoreFromZipBackup' : IDL.Func(
        [IDL.Vec(BackupListingEntry)],
        [ZipRestoreResult],
        [],
      ),
    'restoreListing' : IDL.Func(
        [ListingId],
        [IDL.Variant({ 'ok' : Listing, 'err' : IDL.Text })],
        [],
      ),
    'restoreUserAccountFromBackup' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'rollbackToVersion' : IDL.Func([IDL.Nat], [SiteSettings], []),
    'runLifecycleCleanup' : IDL.Func(
        [],
        [IDL.Record({ 'deleted' : IDL.Nat, 'archived' : IDL.Nat })],
        [],
      ),
    'saveFbCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'scrapeListing' : IDL.Func([IDL.Text], [ScrapeResult], []),
    'setAutoRenewal' : IDL.Func(
        [IDL.Bool, IDL.Nat],
        [IDL.Variant({ 'ok' : GasWallet, 'err' : IDL.Text })],
        [],
      ),
    'setConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'setMaintenanceMode' : IDL.Func([IDL.Bool, IDL.Text, IDL.Text], [], []),
    'setMyUsername' : IDL.Func([IDL.Text], [SetUsernameResult], []),
    'submitSupportTicket' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'toggleListingFavorited' : IDL.Func(
        [ListingId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'toggleListingPinned' : IDL.Func(
        [ListingId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'transformGeminiResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'transformGeminiTestResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'transformPaypalTokenResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'transformStripeAccountResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'transformStripeBackupPaymentIntentResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'transformStripeCheckoutResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'transformStripeCustomerResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'transformStripeGasPaymentIntentResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'transformStripePaymentIntentResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'transformStripePortalResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'transformStripeVerifyResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'triggerAdaptiveAutoBackup' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateAdminSettings' : IDL.Func([UpdateSettingsArgs], [SiteSettings], []),
    'updateListing' : IDL.Func([UpdateListingArgs], [Listing], []),
    'updateMyProfile' : IDL.Func(
        [UpdateProfileArgs],
        [UpdateProfileResult],
        [],
      ),
    'validateDiscountCode' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(DiscountCode)],
        ['query'],
      ),
    'verifyAndGrantPayment' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'verifyEmail' : IDL.Func([IDL.Text], [VerifyEmailResult], []),
  });
};

export const init = ({ IDL }) => { return []; };